### ISSUE TITLE
Wrong display output, when CNF is finished during import

### ISSUE THREAD

**Issue by capiman** [msoos/cryptominisat#235]
echo 1 0 > set_1.cnf
cryptominisat64 --input=set_1.cnf

displays:

...
c [renumber] T:  0.00
c calculated reachability. T: 0.000
c [features] extract T:  T: 0.00
c [features] numVars: 0 numClauses: 0 (numVars/(1.0*numClauses): nan vcg_var_mean: nan vcg_var_std :0.00000 vcg_var_std: 1797
69313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326
88946418276846754670353751698604991057655128207624549009038932894407586850845513394230458323690322294816580855933212334827479
7826204144723168738177180919299881250404026184124858368.00000 vcg_var_max: 0.00000 vcg_var_spread: -1797693134862315708145274
23731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703
53751698604991057655128207624549009038932894407586850845513394230458323690322294816580855933212334827479782620414472316873817
7180919299881250404026184124858368.00000 vcg_cls_mean:nan vcg_cls_std: 0.00000 vcg_cls_min: 179769313486231570814527423731704
35679807056752584499659891747680315726078002853876058955863276687817154045895351438246423432132688946418276846754670353751698
60499105765512820762454900903893289440758685084551339423045832369032229481658085593321233482747978262041447231687381771809192
99881250404026184124858368.00000 vcg_cls_max: 0.00000 vcg_cls_spread :-179769313486231570814527423731704356798070567525844996
59891747680315726078002853876058955863276687817154045895351438246423432132688946418276846754670353751698604991057655128207624
54900903893289440758685084551339423045832369032229481658085593321233482747978262041447231687381771809192998812504040261841248
58368.00000 pnr_var_mean: nan pnr_var_std: 0.00000 pnr_var_min: 1797693134862315708145274237317043567980705675258449965989174
76803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090
389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.0
0000 pnr_var_max: 0.00000 pnr_var_spread: -1797693134862315708145274237317043567980705675258449965989174768031572607800285387
60589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455
133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.00000 pnr_cls_mean: na
n pnr_cls_std: 0.00000 pnr_cls_min: 17976931348623157081452742373170435679807056752584499659891747680315726078002853876058955
86327668781715404589535143824642343213268894641827684675467035375169860499105765512820762454900903893289440758685084551339423
04583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.00000 pnr_cls_max: 0.00000 pn
r_cls_spread: -17976931348623157081452742373170435679807056752584499659891747680315726078002853876058955863276687817154045895
35143824642343213268894641827684675467035375169860499105765512820762454900903893289440758685084551339423045832369032229481658
08559332123348274797826204144723168738177180919299881250404026184124858368.00000 unary: inf binary: nan trinary: nan horn_mea
n: nan horn_std: 0.00000 horn_min: 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558
63276687817154045895351438246423432132688946418276846754670353751698604991057655128207624549009038932894407586850845513394230
4583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.00000 horn_max: 0.00000 horn_s
pread: -179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382
46423432132688946418276846754670353751698604991057655128207624549009038932894407586850845513394230458323690322294816580855933
2123348274797826204144723168738177180919299881250404026184124858368.00000 horn: nan
c [polar] default polars -  pos:       0 neg:       0 undec:       0 T: 0.00
c     0     0       0     0     0     0  0.00  0.00     0     0     0  0.00  0.00

c ------- FINAL TOTAL SEARCH STATS ---------
...

**Comment by a1880** [comment]
A single-line CNF "0 1" is not exactly proper DIMACS.

Nevertheless, I have tried your experiment under Windows.

The output is quite ok:

c Outputting solution to console
c CryptoMiniSat version MSVC-compiled, without GIT
c CryptoMiniSat SHA revision MSVC-compiled, without GIT
c compiled with non-gcc compiler
c Executed with command line:cryptominisat --input=set_1.cnf
c Reading file 'set_1.cnf'
c -- clauses added: 1
c -- xor clauses added: 0
c -- vars added 1
c Parsing time: 0.01 s
c [impl sub] bin: 0 tri: 0 (stamp: 0, cache: 0) T: 0.00 T-out: N w-visit: 2
c [clean] T: 0.0000 s
c [simp] mem usage for occur of irred      0 MB
c [simp] mem usage for occur of red        0 MB
c [simp] Not linked in red 0/0 (0.00 %)
c Mem for watch alloc      : 0           MB (0.00      %)
c Mem for watch array      : 0           MB (0.00      %)
c [str] sub: 0 str: 0 tried: 0/0 (-1.$%) T: 0.00 T-out: N
c Empty resolvent elimed: 0 T: 0.00 T-out: N
c  #try to eliminate: 0
c  #var-elim: 0
c  #T-o: N
c  #T-r: 100.00%
c  #T: 0.00
c [str] sub: 0 str: 0 tried: 0/0 (-1.$%) T: 0.00 T-out: N
c [clean] T: 0.0000 s
c [occur] 0.0000 is overhead
c [v-elim] elimed: 0 / 0 / 0 T: 0.00 T-out: N
c [v-elim] cl-new: 0 tried: 0 tested: 0 (0.0000 % aggressive)
c [v-elim] subs: 0 red-bin rem: 0 red-tri rem: 0 red-long rem: 0 v-fix:    0
c [simp] link-in T: 0.0000 cleanup T: 0.0000
c [cache] cleaned. Updated:       0 K Cleaned:       0 K Freed:       0 K T: 0.00
c [scc] new: 0 BP 0M T: 0.00
c [clean] T: 0.0000 s
c [vrep] vars 0 lits 0 rem-bin-cls 0 rem-tri-cls 0 rem-long-cls 0 BP 0M T: 0.00
c [cache] cleaned. Updated:       0 K Cleaned:       0 K Freed:       0 K T: 0.00
c [clean] T: 0.0000 s
c [renumber] T:  0.00
c calculated reachability. T: 0.000
c [polar] default polars -  pos:       0 neg:       0 undec:       0 T: 0.00
c     0     0       0     0     0     0  0.00  0.00     0     0     0  0.00  0.00
c ------- FINAL TOTAL SEARCH STATS ---------
c UIP search time          : 0.00        (0.00      % time)
c restarts                 : 1           (0.00      confls per restart)
c blocked restarts         : 0           (0.00      per normal restart)
c time                     : 0.00        
c decisions                : 0           (0.00      % random)
c decisions/conflicts      : -1.#J       
c CONFLS stats
c conflicts                : 0           (0.00      / sec)
c conflsBinIrred           : 0           (0.00      %)
c conflsBinRed             : 0           (0.00      %)
c conflsTriIrred           : 0           (0.00      %)
c conflsTriIrred           : 0           (0.00      %)
c conflsLongIrred          : 0           (0.00      %)
c conflsLongRed            : 0           (0.00      %)
c LEARNT stats
c units learnt             : 0           (0.00      % of conflicts)
c bins learnt              : 0           (0.00      % of conflicts)
c tris learnt              : 0           (0.00      % of conflicts)
c long learnt              : 0           (0.00      % of conflicts)
c otf-subs                 : 0           (0.00      /conflict)
c otf-subs implicit        : 0           (0.00      %)
c otf-subs long            : 0           (0.00      %)
c otf-subs learnt          : 0           (0.00      % otf subsumptions)
c otf-subs lits gained     : 0           (0.00      lits/otf subsume)
c SEAMLESS HYPERBIN&TRANS-RED stats
c advProp called           : 0           
c hyper-bin add bin        : 0           (0.00      bin/call)
c trans-red rem irred bin  : 0           (0.00      bin/call)
c trans-red rem red bin    : 0           (0.00      bin/call)
c CONFL LITS stats
c orig                     : 0           (0.00      lit/confl)
c rec-min effective        : 0           (0.00      % attempt successful)
c rec-min lits             : 0           (0.00      % less overall)
c further-min call%        : 0.00        (0.00      % attempt successful)
c bintri-min lits          : 0           (0.00      % less overall)
c cache-min lits           : 0           (0.00      % less overall)
c stamp-min call%          : 0.00        (0.00      % attempt successful)
c stamp-min lits           : 0           (0.00      % less overall)
c final avg                : 0.00        
c all-threads sum CPU time : 0.00         s
c PROP stats
c Mbogo-props              : 0.00        (0.00      / sec)
c MHyper-props             : 0.00        (0.00      / sec)
c Mprops                   : 0.00        (0.00      / sec)
c props/decision           : -1.#J       
c props/conflict           : -1.#J       
c ------- FINAL TOTAL SOLVING STATS END ---------
c ------ REDUCEDB STATS ---------
c reduceDB time            : 0.00        (0.00      % time)
c cleaned cls              : 0           (0.00      % long redundant clauses)
c cleaned lits             : 0           (0.00      % long red lits)
c cleaned cl avg size      : 0.00        
c cleaned avg glue         : 0.00        
c remain cls               : 0           (0.00      % long redundant clauses)
c remain lits              : 0           (0.00      % long red lits)
c remain cl avg size       : 0.00        
c remain avg glue          : 0.00        
c ------ REDUCEDB STATS END ---------
c reachability time        : 0.00        (0.00      % time)
c ------- REACHABILITY STATS -------
c time                     : 0.00        
c dominator lits           : 0.00        % of unknowns lits
c dependent lits           : 0.00        % of unknown lits
c avg num. dominated lits  : 0.00        
c ------- REACHABILITY STATS END -------
c 0-depth assigns          : 1           (0.00      % vars)
c 0-depth assigns by searcher: 0           (0.00      % vars)
c 0-depth assigns by CNF   : 1           (0.00      % vars)
c probing time             : 0.00        (0.00      % time)
c -------- PROBE STATS ----------
c probe time               : 0.00        (0.00      (Mega BP+HP)/s)
c called                   : 0           (0.00      s/call)
c unused Mega BP+HP        : 0.00        (0.00      est. secs)
c 0-depth-assigns          : 0           (0.00      % vars)
c bothsame                 : 0           (0.00      % visited)
c probed                   : 0           (0.00      probe/sec)
c loop iters               : 0           (0.00      % var probed)
c failed                   : 0           (0.00      % of probes)
c visited                  : 0.00        M lits (0.00      % of available lits)
c bin add                  : 0           (0.00      % of bins)
c irred bin rem            : 0           (0.00      % of bins)
c red bin rem              : 0           (0.00      % of bins)
c time                     : 0.00        s
c CONFLS stats
c conflicts                : 0           (0.00      / sec)
c conflsBinIrred           : 0           (0.00      %)
c conflsBinRed             : 0           (0.00      %)
c conflsTriIrred           : 0           (0.00      %)
c conflsTriIrred           : 0           (0.00      %)
c conflsLongIrred          : 0           (0.00      %)
c conflsLongRed            : 0           (0.00      %)
c PROP stats
c Mbogo-props              : 0.00        (0.00      / sec)
c MHyper-props             : 0.00        (0.00      / sec)
c Mprops                   : 0.00        (0.00      / sec)
c -------- PROBE STATS END ----------
c Simplifier time          : 0.00        (0.00      % time)
c -------- Simplifier STATS ----------
c time                     : 0.00        (0.00      % var-elim)
c timeouted                : 0.00        % called
c called                   : 1           (0.00      s per call)
c v-elimed                 : 0           (0.00      % vars)
c v-elimed: 0 / 0 / 0
c 0-depth assigns          : 0           (0.00      % vars)
c cl-new                   : 0           
c tried to elim            : 0           (0.00      % aggressively)
c elim-bin-lt-cl           : 0           
c elim-tri-lt-cl           : 0           
c elim-long-lt-cl          : 0           
c lt-bin added due to v-elim: 0           
c cl-elim-bin              : 0           
c cl-elim-tri              : 0           
c cl-elim-long             : 0           
c cl-elim-avg-s            : -1.#J       
c v-elim-sub               : 0           
c -------- Simplifier STATS END ----------
c -------- GATE FINDING ----------
c time                     : 0.00        
c find gate time           : 0.00        (0.00      % time)
c gate-based cl-sh time    : 0.00        (0.00      % time)
c gate-based cl-rem time   : 0.00        (0.00      % time)
c gate-based varrep time   : 0.00        (0.00      % time)
c gatefinder cl-short      : 0           (0.00      % long cls)
c gatefinder lits-rem      : 0           (0.00      % long cls lits)
c gatefinder cl-rem        : 0           (0.00      % long cls)
c gatefinder cl-rem's lits : 0           (0.00      % long cls lits)
c gatefinder var-rep       : 0           (0.00      % vars)
c -------- GATE FINDING END ----------
c SCC time                 : 0.00        (0.00      % time)
c ----- SCC STATS --------
c time                     : 0.00        (0.00      per call)
c called                   : 1           (0.00      new found per call)
c found                    : 0           (0.00      % of all found)
c bogoprops                : 0           % of all found
c ----- SCC STATS END --------
c --------- VAR REPLACE STATS ----------
c time                     : 0.00        (0.00      per call)
c trees' crown             : 0           (0.00      % of vars)
c 0-depth assigns          : 0           (0.00      % vars)
c lits replaced            : 0           
c bin cls removed          : 0           
c tri cls removed          : 0           
c long cls removed         : 0           
c long lits removed        : 0           
c bogoprops                : 0           
c --------- VAR REPLACE STATS END ----------
c vrep replace time        : 0.00        (0.00      % time)
c vrep tree roots          : 0           
c vrep trees' crown        : 0           (-1.#J     leafs/tree)
c distill time             : 0.00        (0.00      % time)
c -------- DISTILL STATS --------
c time                     : 0.00        (0.00      per call)
c timed out                : 0           (0.00      % of calls)
c distill/checked/potential: 0          /0/0
c lits-rem                 : 0           
c 0-depth-assigns          : 0           (0.00      % of vars)
c -------- DISTILL STATS END --------
c strength cache-irred time: 0.00        (0.00      % time)
c strength cache-red time  : 0.00        (0.00      % time)
c -------- STRENGTHEN STATS --------
c --> cache-based on irred cls
c time                     : 0.00        (0.00      s/call)
c shrinked/tried/total     : 0          /0/0
c subsumed/tried/total     : 0          /0/0
c lits-rem                 : 0           (0.00      % of lits tried)
c called                   : 0           (0.00      % ran out of time)
c --> cache-based on red cls
c time                     : 0.00        (0.00      s/call)
c shrinked/tried/total     : 0          /0/0
c subsumed/tried/total     : 0          /0/0
c lits-rem                 : 0           (0.00      % of lits tried)
c called                   : 0           (0.00      % ran out of time)
c -------- STRENGTHEN STATS END --------
c -------- IMPLICIT SUB STATS --------
c time                     : 0.00        (0.00      per call)
c timed out                : 0           (0.00      % of calls)
c rem bins                 : 0           
c rem tris                 : 0           
c -------- IMPLICIT SUB STATS END --------
c --------- Implication Cache Stats Start ----------
c lits having cache        : 0.00        % of decision lits
c num elems in cache/lit   : 0.00        extralits
c --------- Implication Cache Stats End   ----------
c Conflicts in UIP         : 0           (0.00      confl/TOTAL_TIME_SEC)
c Total time               : 0.01        
c Mem used                 : 0           MB
c Mem for longclauses      : 0           MB (0.00      %)
c Mem for watch alloc      : 0           MB (0.00      %)
c Mem for watch array      : 0           MB (0.00      %)
c Mem for assings&vardata  : 0           MB (0.00      %)
c Mem for impl cache       : 0           MB (0.00      %)
c Mem for stamps           : 0           MB (0.00      %)
c Mem for history stats    : 0           MB (0.00      %)
c Mem for search&solve     : 0           MB (0.00      %)
c Mem for renumberer       : 0           MB (0.00      %)
c Mem for component handler: 0           MB (0.00      %)
c Mem for simplifier       : 0           MB (0.00      %)
c Mem for xor-finder       : 0           MB (0.00      %)
c Mem for varReplacer&SCC  : 0           MB (0.00      %)
c Mem for prober           : 0           MB (0.00      %)
c Accounted for mem (rss)  : 0.00        %
c Accounted for mem (vm)   : 0.00        %
s SATISFIABLE
v 1 0

**Comment by capiman** [comment]
Hi Axel,
thanks for retesting. The used CNF was only a reduction to a simple case, I saw it with a bigger
well-formed CNF. I also used Windows, but compiled with a MinGW 64 Bit compiler instead of MSVC.
You are using MSVC?
Can you please check, if you have feature_fast.cpp included in your build?
Do you use latest sources or some earlier version?
Best regards,
Martin

PS: I see e.g. the following difference in output:

On your side:
c [str] sub: 0 str: 0 tried: 0/0 (-1.$%) T: 0.00 T-out: N

On my side:
c [str] sub: 0 str: 0 tried: 0/0 (nan%) T: 0.00 T-out: N

Hopefully your compiler means with "-1.$" the same thing as "nan"...

**Comment by a1880** [comment]
I compiled with MS VC++ 2013 on 26-May-2015
feature_fast.cpp is neither known to me nor included.

**Comment by capiman** [comment]
Have a look at latest sources. File was included just around 1 week ago.

**Comment by a1880** [comment]
Probably not possible for me this weekend.

My suggestion is to focus on tests with valid and meaningful input files.
A waterproof Cryptominisat would be nice, but a solver for my problems would be even nicer.
The SAT competions disregard beauty and perfection. They solely honor results.
