### ISSUE TITLE
--maxconfl and --threads=x is a bad combination, could take endless

### ISSUE THREAD

**Issue by capiman** [msoos/cryptominisat#272]
Some threads are faster, some seem to be really slow in counting conflicts.
One thread after the other is stopping, but other are still calculating...
Perhaps check and reject this combination?
Or set must_interrupt_asap, when first is breaking the conflict limit?

In this case --maxtime is much better :-)

**Comment by msoos** [comment]
Yes, this is normal. You are capping the number of conflicts, not the number of total conflicts. There is nothing that can be done about this. The user must use maxtime in this case. maxconfl is not useful anyway, since it's mainly for reproducibility but that is impossible in a multi-threaded setting anyway.
