### ISSUE TITLE
How to limit the number of variables ???

### ISSUE THREAD

**Issue by baston007** [msoos/cryptominisat#273]
I have a problem with the software which generates source code for Cryptominisat.  I seem to be generating one, or more variables with huge ID numbers.  Is there any way to limit the maximum size of a variable number within Cryptominisat.  It appears that Cryptominisat reverses memory for all possible variables between 1 the whatever the largest value in the set is.  In my case, entering a bogus huge variable number fills all of memory, then starts filling swap space.  The end result is a reboot.  It would be great if a too large variable number were entered, Cryptominisat would just generate an error message and exit.  Is this possible, and how?

**Comment by a1880** [comment]
You could use the cnf-renumber utility as a preprocessing step.
Link: https://github.com/msoos/cnf-utils

**Comment by msoos** [comment]
Sorry to say but this will not be fixed. Your problem generation is
incorrect :( This is not an issue with the solver: No solver will do what
you need because they cannot possibly fix all the issues with the input .
You need to get the input right and then the solver can help you deliver
the rest :)

You may want to try what Axel pointed you at. But that is really a stopgap
measure and I don't guarantee  it will work. In general you need to fix
your input. Good luck!

Mate
