### ISSUE TITLE
New parser issues

### ISSUE THREAD

**Issue by msoos** [msoos/cryptominisat#282]
First of all, thanks!  I have fixed some minor issues, e.g. the parsing of integers was not checking that it's really an integer that's given. Similarly for floats/doubles. It now also checks for range (-2 given to unsigned is an issue). Also, giving "--debuglib --maxconfl" was ambiguous so I disallow starting with "--" I should probably disallow "--debuglib -h" too, where "-h" is taken as a string option to "--debuglib"

The main issue I have at the moment is that it leaks memory, so my valgrind checks all fail. This is quite bad because I like my valgrind checks :) 

Please see https://gist.github.com/msoos/569bc54663055fc2f9da for a full log :)

**Comment by msoos** [comment]
A _very_ minor issue I have is e.g. I cannot report the option name from value-parsing which would be useful for "--debuglib --maxsol". The %xxx% magic doesn't quite work and it's cumbersome. Similarly for integer/float parsing, the passing of the failing value isn't perfect and I didn't manage to get it to quite work. However, this can be fixed much later, when the option parser is already in mainline.

**Comment by msoos** [comment]
Please see https://github.com/msoos/cryptominisat/tree/axelparser for the branch that is tracking this and please try to send diffs relative to that :) Try using git. It's pretty neat!

**Comment by msoos** [comment]
[ Oh, another thing I fixed is the getoptlong returns ':' in case the argument is missing. It now checks for that :) ]

**Comment by msoos** [comment]
Also, can we please move to indentation of 4 spaces instead of tabulators? It'd make my life easier... :) We don't have to for the moment, but the end result would be easier to handle...

**Comment by msoos** [comment]
Also, bool_switch is not handled correctly. `./cryptominisat --zero-exit-status input.cnf` is supposed to toggle zero-exit-status to TRUE and parse in input.cnf. Instead, it eats the parameter "input.cnf" as a parameter to `--zero-exit-status`. Could you please fix this?

**Comment by a1880** [comment]
I am treating bool_switch like a Value<bool> with implicit value true.

However, a value may be explicitely given on the commandline.

I modified getopt_long to assume that there is an explicit value, unless the parameter starts with ‘-‘.

So, it probably would be better to change option_description.cpp, so that bool_switch options have no explicit option values.

 

 

Von: Mate Soos [mailto:notifications@github.com] 
Gesendet: Samstag, 10. Oktober 2015 22:35
An: msoos/cryptominisat
Betreff: Re: [cryptominisat] New parser issues (#282)

 

Also, bool_switch is not handled correctly. ./cryptominisat --zero-exit-status input.cnf is supposed to toggle zero-exit-status to TRUE and parse in input.cnf. Instead, it eats the parameter "input.cnf" as a parameter to --zero-exit-status. Could you please fix this?

**Comment by a1880** [comment]
Could the memory leak be due to the fact that I am constructing an array of “struct option” items passed

to getopt_long and not freed afterwards?

 

The array is filled in parsers.cpp  basic_parsed_options::long_options()

 

A check would be to compare the valgrind log entries with the options (one entry per option?).

 

Von: Mate Soos [mailto:notifications@github.com] 
Gesendet: Samstag, 10. Oktober 2015 21:30
An: msoos/cryptominisat
Betreff: [cryptominisat] New parser issues (#282)

 

First of all, thanks! I have fixed some minor issues, e.g. the parsing of integers was not checking that it's really an integer that's given. Similarly for floats/doubles. It now also checks for range (-2 given to unsigned is an issue). Also, giving "--debuglib --maxconfl" was ambiguous so I disallow starting with "--" I should probably disallow "--debuglib -h" too, where "-h" is taken as a string option to "--debuglib"

The main issue I have at the moment is that it leaks memory, so my valgrind checks all fail. This is quite bad because I like my valgrind checks :) 

Please see https://gist.github.com/msoos/569bc54663055fc2f9da for a full log :)

**Comment by a1880** [comment]
Obviously, I should use git.

I have tried several tutorials, but I am still unsure about the best recipe / development cycle.

 

Von: Mate Soos [mailto:notifications@github.com] 
Gesendet: Samstag, 10. Oktober 2015 21:33
An: msoos/cryptominisat
Betreff: Re: [cryptominisat] New parser issues (#282)

 

Please see https://github.com/msoos/cryptominisat/tree/axelparser for the branch that is tracking this and please try to send diffs relative to that :) Try using git. It's pretty neat!

**Comment by msoos** [comment]
:I Here is how:

1) Go to Cryptominisat, switch to axeloptions branch, click clone.
2) Get git
3) add your ssh key to github
4) go to your page, clone your own repository: git clone ....
5) "cd cryptominisat"
6) check which branch you are on: "git branch"
7) if not axeloptions, then: "git checkout axeloptions"
8) change code
9) "git diff" to see what changed
10) "git commit -a -m 'my message'" to commit
11) git push to push it to your repository
12) go to your repository and "create github merge request" (google it
13) Done! Lucky 13! :D

**Comment by a1880** [comment]
Well, that sounds doable indeed.
Are clone and fork synonyms?
What happens if there are any changes in your branch I want to transfer to my fork? Do I have to fork again, or can I update my fork?

**Comment by msoos** [comment]
Do not transfer anything from my branches :) Just work on yours and it will magically work when I merge. The moment you merge my changes into your changes it's going to be hell on earth. Then I need to merge your changes into my changes that already contain my changes. And that's hell. So, just concentrate on your stuff :)

Yes, just clone my repo into your repo (="fork" in github) and then clone it to your local computer (using git clone) and then work on it and then commit and push. Good luck!

**Comment by msoos** [comment]
The only issue I have now is that long options get matched even if they are not fully written (e.g '--o" would get mached for "--output" or somesuch). I have re-pushed my branch. Unfortunately I messed up and you can't merge it with your own, so you need to re-pull the whole branch. Can you please take a look why that issue is there? Other than that, we could move to that branch right now :) Would be REALLY nice to have statically compiled executables that you can use out-of-the-box, no need to recompile them :)

**Comment by a1880** [comment]
I think I have found the culprit. In getopt_long.cpp near line 192, the so far "best match" is remembered which in fact enables abbreviated options. If this is not desirable, remove the two lines "if (match == -1) match = i;".  
In variables_map.cpp, MS VC++ complains about "strdup()" in line 54. This should be "_strdup()" to be POSIX compliant. It might be elegant to put this in the global include for MS VC++.

**Comment by msoos** [comment]
Woooow! This I think is the last straw here :) I will do some tests, see what may be off, but I think we are now done. I will merge this into master and we can finally get rid of boost, yay! This means we can generate static binaries for Windows automagically with AppVeyor and static binaries for Linux with TravisCI. Great work, thanks!
