### ISSUE TITLE
Consolidate step takes long time on big CNF... (35 minutes)

### ISSUE THREAD

**Issue by capiman** [msoos/cryptominisat#315]
Running with 2 thread and very big CNF...
The consolidate step takes 2101 seconds (=35 minutes).
Can you tell what it is doing during consolidate? Seems to operate on watch_array and watches. shrink_to_fit. Something like duplicate removal or something different?
Are watch_array and watches for binaries? And tris? On this case on IrrB and IrrT?
It looks like this is taking so long every time (--dumpirred=xxx.cnf and reading it in next time).
Worth waiting so long or option to switch it off? Worth a timeout?

```
c 1455643932 c Reading file 'e2_irred_48.cnf'
c 1455644634 c -- clauses added: 688216049
c 1455644634 c -- xor clauses added: 0
c 1455644634 c -- vars added 130180
...
c 1455644634 c Parsing time: 702.83 s
...
c 1455644672 c [scc] new: 2 BP 344M T: 2.11
c 1455646774 c [consolidate] T: 2101.19
c 1455646774 c calculated reachability. T: 0.003
c 1455646787 c [polar] default polars -  pos:      40 neg:  130133 undec:       7 T: 4.69
c 1455646881 c [w-sort]  T: 18.54
c 1455646903 c  rest  conf freevar  IrrL  IrrT  IrrB l/longC  l/allC  RedL  RedT  RedB l/longC  l/allC
c 1455646903 c    43  7001  130175   266 2742K  685M  489.65    2.00  6984     5    12  817.96  815.98
```

**Comment by capiman** [comment]
BTW: CMS4 consuming ~ 24 GByte during calculation... :-)

**Comment by msoos** [comment]
First of all, thanks for the report, this is quite useful and surprising!

Wow. I'd turn it off. Note that CMS was not optimized to work on instances like that. I am not sure what you are trying to solve exactly, but unless you have had previous real success with the method, you may want to re-evaluate your approach. Otherwise, if you are trying to solve a problem that has never been solved before, I suggest you try solving smaller versions of the problem first.

I'll think about how to address the issue of this operation taking 35 minutes. Until then, I'll keep this issue open so you know what I'm doing.

**Comment by capiman** [comment]
Perhaps this code is a bit faster (vec.h):
(in my current test I get a speed up of factor 2 to 4, 
from ~1600s with malloc and memcpy
to ~400s to ~700s with realloc only)

```
    void shrink_to_fit()
    {
#if 0
        T* _data2 = (T*)malloc(sz*sizeof(T));
        if (!_data2) {
            throw std::bad_alloc();
        }
        memcpy(_data2, _data, sz*sizeof(T));
        free(_data);
        _data = _data2;
#endif // 0

        if (sz > 0)
        {
          _data = (T*)realloc((void *)_data, sz*sizeof(T));
          if (!_data) {
              throw std::bad_alloc();
          }
        }
        else
        {
          free((void *)_data);
          _data = NULL;
        }

        cap = sz;
    }
```

A malloc with sz=s is a malloc(0), which seems to be dependant on library implementation
("If size is zero, the return value depends on the particular library implementation (it may or may not be a null pointer), but the returned pointer shall not be dereferenced.")

See
http://www.cplusplus.com/reference/cstdlib/malloc/

My code explicitly set _data to NULL, when sz==0.

Was there a specific reason why no realloc was used?
Perhaps due to fragmentation problems?
In my opinion realloc can perhaps skip the copy part, if area is made smaller
and same memory can be used before and afterwards (only a bit smaller).

Other idea could be that effectiveness of shrink_to_fit is tested during first x elements,
and continue only if it is really effective. I think there are similar ideas already in cases like
"c [intree] too expensive SCC + varreplace loop: aborting".

**Comment by a1880** [comment]
Thrilled by the speedups you observed, I have conducted a set of experiments (with 5 repetitions per test) based on Cryptominisat 4.5.3 with and without realloc in vec.h

The good news: it works without noticable problems (for 8 threads, compiled under Windows with Microsoft Visual C++ 2015).

However, I cannot reproduce any major speedup. 

My largest sample problem (2.6mb CNF, with 41553 variables and 139968 clauses) took 12.45s with realloc and 12.51s with free+malloc. But for smaller examples, I am getting the opposite effect, probably due to measurement fluctuation.

**Comment by msoos** [comment]
Sorry, but that patch goes around the original intent of the code: to actually free things up. However, you can just disable shrink_to_fit if you feel like it. Just comment it all out. It will still work completely fine. Can you please check if this is the only thing that is making consolidate() slow? Are there any other things?

Thanks!

**Comment by a1880** [comment]
In theory, realloc should be more efficient than malloc+copy+free and should lead to less-fragmented memory. I noticed that shrink_to_fit is referenced in 34 places and called in loops. So, it might well be worth tuning it. However, I have not been able to find any evidence that realloc actually is an improvement here.

**Comment by msoos** [comment]
Thanks, fixed! The realloc is a good idea.

On a more general note, though. There are a lot of places to fix CryptoMiniSat. Memory reallocation and other neat fixes are great, but I think there are other places that could gain more. For this specific problem, 35minutes is a lot, it was a bug, and it's grate to have it fixed :) But in general CrypoMiniSat is outdone not because of the realloc issue, I think. It's outdone mostly because the heuristics needs to be tuned and some important ideas are not yet implemented. It'd be great to see some, such as blocked clause elimination, implemented -- I think it could bring a lot of benefits.

Thanks a lot for the discussion above and the fix :)

Mate
