### ISSUE TITLE
Dump of clauses isnt possible even with disabled BVA. XOR-Problem?

### ISSUE THREAD

**Issue by SmallLars** [msoos/cryptominisat#328]
When I started to add XOR-Clauses with 5 literals, I am not longer able to dump the clauses after run. The following error appears: "ERROR: cannot make meaningful dump with BVA turned on."
Maybe root cause is line 286 in solver.cpp: "new_var(true);". BVA is always enabled there.
Is it possible to change that to the configuration value?

**Comment by msoos** [comment]
Thanks for the report! It's a bit more complicated than that :) I'll get
back to you tonight and offer a potential workaround. Cheers!

**Comment by msoos** [comment]
The issue is the following, really: you are asking a solver to dump you CNF. But you added XORs into the solver. How can the solver give you CNF? Well, there are two ways:

- it gives you XOR claues. Obviously, that's not a good idea, since dumping the CNF is done so that you can import it into another solver
- it gives you a pure CNF. This means the solver converts the XOR into CNF. That can only be done  (within sanity) if you cut up the XOR. But for that, you need to add extra variables. Hence BVA (bounded variable addition) is used.

So... we are stuck. Pick one of the two :) If you are happy with extra variable(s) in your CNF, pick (2), if you are not, you'd pick (1). Unfortunately, (1) is not available because to keep some of my sanity (and there is not much of that left), I am using (2) internally inside the solver. So... this means you either accept (1), or super-hackishly, change line 267 in solver.cpp:
```
for(; at < last_at+2 && at < lits.size(); at++) {
```

into:

```
for(; at < last_at+4 && at < lits.size(); at++) {
```

and you convert up to 6-long XORs into normal clauses (which is a lot of clauses). There is simply no other way, other than re-writing every single simplification pass (about 20k lines of code) to handle XOR clauses. If you did that, I'll be happy of course :) 

Good luck!

Mate

**Comment by SmallLars** [comment]
Thank you very much :)

I am not sure if I understand how CMS is working. "re-writing every single simplification pass" means to extend simplification for longer XORs or to add XOR support in general?

In the first case: Will longer XORs be ignored in simplification when I use your super-hackishly solution?
If the last case is true: CMS converts every XORs in normal clauses already on input time or ignore XORs in simplification in general?

In my opinion everyone who use CMS with XORs would expect XORs in the output to.
Your statement "you are asking a solver to dump you CNF" is wrong. I am asking the solver to dump the clauses. A special case of that is the CNF. For usage with other solvers there can be an additional parameter in the "open_file_and_dump_*_clauses" functions to enable/disable XOR conversion on output. Maybe I am wrong with that, would be interesting to hear your meaning.

**Comment by msoos** [comment]
To add XOR support to simplifications in general. I expect this to take about 2-3 researchers about 3-4 years of time, i.e. about 1 million USD. If you have that kind of funding, please let me know.

No, the hackish solution will work. The XOR will be dumped as CNF (and recovered in case of need by CryptoMiniSat and other solvers)

Unfortunately XORs cannot be dumped because they are internally only temporarily stored as XORs. They are usually stored as normal clauses instead. This is actually a huge benefit. You could, however, dump the XORs as CNF with the extra variables. But the CNF will then contain extra variables which were originally not part of the problem. If that is OK with you, you can easily edit the code to do that.

I wish you good luck and/or deep pockets! :)

Mate
