### ISSUE TITLE
extreme runtime variation in scalmc

### ISSUE THREAD

**Issue by dfremont** [msoos/cryptominisat#361]
This could easily not be a bug at all, but I thought I'd post an issue so that you have something concrete if you have a chance to look into it. As I've mentioned to you before, in the past we've noticed that the runtime of CryptoMiniSat varies substantially depending on which random XOR clauses are added in (older versions of) scalmc. Obviously this is to be expected, but what is strange is that while the runtime variation is often not so great (maybe a factor of two or three), there are sometimes outliers that seem to take forever (or at least much longer than usual).

Here's a concrete example you can reproduce. On [this benchmark](https://github.com/dfremont/counting-benchmarks/blob/master/benchmarks/projection/misc/misc-2/all/hash-11.cnf.gz), run the command

`scalmc --pivotAC 60 --tApproxMC 1 --random R --looptout 28800 hash-11.cnf`

with the latest version (2cca022) of CryptoMiniSat and R ranging from 0 to 7. On my machine, this takes from 16 to 38 minutes for R = 1, 3, 4, and 6. But for R = 0, 2, 5, and 7, it times out after 8 hours. If this is just due to some XOR clauses being much harder than others, it shows the importance of having a good timeout-and-retry mechanism in scalmc - but it could be a bug. When I have time, I will try to do similar experiments with different benchmarks to see if this behavior occurs generically.

**Comment by dfremont** [comment]
I've tried a few more benchmarks, and so far have only seen this happen with [one other benchmark](https://github.com/dfremont/counting-benchmarks/blob/master/benchmarks/projection/misc/misc-1/B/01B-3.cnf.gz), but it's a completely different type from the one above. With the same type of command as above, R = 0, 1, 2, 5, and 6 take 7-10 minutes, while R = 3, 4, and 7 run for at least 4 hours.

**Comment by msoos** [comment]
First of all, thank you so much for the detailed analysis!

The truth of the matter is that I read Tero's paper (his PhD thesis, ALL about Gauss: https://aaltodoc.aalto.fi/bitstream/handle/123456789/14418/isbn9789526059457.pdf?sequence=1 ) and I realised I'm doing something wrong. I mean, the integration is perfect. That's how it's supposed to be -- keeping things CNF and recovering XORs, etc. That gives us a big boost. But I need to pivot, and I need to use a different mechanism for calculating propagations. This will not only be better in a linear way. It will be better in a potentially exponential way. So:

* I've been doing things wrongly
* There is potential for real speedup
* It's only marginally publishable as it's mostly Tero's work

Anyway, at least it will be good. The issue is that this will take time. Unfortunately, nobody is willing to implement any of this. It's time and there is simply "no scientific benefit" -- meaning, of course, you can't publish, so why bother? Anyway, so there we are. In time it will be done. I'll be working on this.

**Comment by sliedes** [comment]
I thought about opening a new issue, but this is so close that it may be the same issue even if my input doesn't really have explicit XORs.

I've been benchmarking cryptominisat5 -t 4 on a toy problem (for a 2-round variant of AES-128, find input and key such that input == output) generated using cbmc, which takes around 6.7 seconds on average on my computer (7.8 s on cryptominisat5-gauss). The resulting distribution of run times looks... funny, not anything like a probability distribution with a single peak.

Plot of distribution:

![cryptominisat5_times](https://cloud.githubusercontent.com/assets/2307997/17442986/ff1f2f9c-5b40-11e6-8e8a-a5f3fc3e905e.png)

Same with logarithmic axis:

![cryptominisat5_times_log](https://cloud.githubusercontent.com/assets/2307997/17443073/572c9fee-5b41-11e6-8dc2-9c181dd3ca20.png)

For example for plingeling the distribution is much smoother (but it's a lot slower on the problem):

![plingeling_times](https://cloud.githubusercontent.com/assets/2307997/17443063/49cf29e8-5b41-11e6-979f2-0e4bc3974643.png)

The input file:

[eq2.zip](https://github.com/msoos/cryptominisat/files/404169/eq2.zip)

**Comment by msoos** [comment]
Sorry, but that has nothing to do with this. Unfortunately, SAT solvers are highly , and 6s vs 35s is in fact extremely small variation. I can show you problems that have 1s vs 5000s and it's considered normal -- by the best in the field. This latter one is a satisfiable problem, that can have HUGE variations. For unsatisfiable ones, it's usually a lot more stable, but 6s vs 35s would be considered extremely close. This is how it works. When it comes to multi-threading, things get even more hazy. Anyway, this has nothing to do with the issue raised here. Sorry about that. Gaussian elimination is an experimental thing, and it has a number of weird cases where 100s vs 5000s  (+timeout) was the issue. So that's concerning, especially given that it's experimental code. I'm sorry I couldn't help you. However, I'm glad that CryptoMiniSat is a lot faster than plingeling! That's good news :)

**Comment by sliedes** [comment]
Ah, yes, I know this. Maybe I should have been more specific that what surprises me is not the variance (the width of the distribution), but its shape. Like, why is it 100 times more common to see either 8 seconds or 16 seconds than 13 seconds.

**Comment by sliedes** [comment]
For some reason, the plingeling distribution doesn't show, so let's try again. Comparing to it shows the point quite nicely, I think. The variance there is even larger, like 2..170 seconds, but the distribution has a much more regular shape centered around 30 or so seconds.

![plingeling_times](https://cloud.githubusercontent.com/assets/2307997/17451748/e5b17b56-5b71-11e6-8eee-afa5a9fc93cd.png)

**Comment by msoos** [comment]
Because CMS does simplification rounds in batches. It usually cannot solve the system while doing the simplification. So you get a rugged terrain. If you switch it off, it will be fine ("--simp 0", "--presimp 0" and maybe some others). Again, please let us not put noise into this issue. This issue is actually valid and again, has nothing to do with what you are describing. Sorry, but I like to keep issues separate, and it is very disrespectful to the person who opened the bugreport to hijack the topic.

**Comment by msoos** [comment]
Ah, I'm coming back to this. Should be a LOT better once I do this right. I'm sorry I have been so lazy at trying to do the right thing.

**Comment by msoos** [comment]
OK, I think I have fixed this. Please use the "simpsat" branch. Also, please do not publicise. This stuff blows anything out of the water.
