### ISSUE TITLE
Add a release tag for 5.0.0 release.

### ISSUE THREAD

**Issue by arrowd** [msoos/cryptominisat#362]
There are tags for 2.9.11 and 4.5.3, but the tag for 5.0.0 is called "cryptominisat-5.0.0". Have it been "5.0.0", it would be more comfortable for distribution packagers (like me).

**Comment by msoos** [comment]
The problem is, if it's tagged as 5.0.0, then the downloadable source tarball from GitHub is called "5.0.0.tar.gz" which is not what most people expect. I can also add a tag 5.0.0 though, which I just did :) I hope it helps! I'll tag it from now on with both.

Please let me know what distribution you are trying to package CMS for :)

Thanks!

Mate

**Comment by arrowd** [comment]
>  then the downloadable source tarball from GitHub is called "5.0.0.tar.gz" which is not what most people expect.

Turns out this has been so for so long that now people (at least we at FreeBSD) do expect. As you might guessed, i'm packaging (updating, actually) CMS for FreeBSD: [http://www.freshports.org/math/cryptominisat/](http://www.freshports.org/math/cryptominisat/)

**Comment by msoos** [comment]
Cool, thanks for the explanation! And thanks for packaging :)
