### ISSUE TITLE
Memory manager exception?

### ISSUE THREAD

**Issue by cipherboy** [msoos/cryptominisat#384]
```
$ time ~/GitHub/cryptominisat/cryptominisat5 --maxtemp 300000 --cachesize 8192 --cachecutoff 8000
 --threads 2 ./sat2.cnf > sat2.out
ERROR: memory manager can't handle the load size: 1073741594 needed: 1489 newcapacity: 1073741823
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

real    4485m13.206s
user    8404m1.308s
sys     23m20.052s
```

In particular, cachesize, cachecutoff are 4x existing limits, maxtemp is 10x existing limit. I can attach the .cnf file if you are interested. Thoughts about debugging this? I've been trying to play around with the parameters to increase memory utilization on longer running models. I should have plenty of memory -- process typically consumes less than 4GB, total is 32GB.

Also, is this a problem with the code or my model/invocation parameters?

**Comment by msoos** [comment]
What might be happening is that your problem is generating a lot of very large clauses (hundreds or thousands of literals/learnt clause). The system is not really capable of dealing with that for such a long while, it will run out of bits in the clause pointer -- which is bit-stuffed to have only 30b of usable space. It's currently requesting over 2**30 4-byte memory pieces. Essentially, the system is not able to address that much memory. Sorry, this is a constraint on the system so it can use 32b "pointers" for memory instead of 64, which would make it slower due to cache being effectively halved.

I suggest you start with less than 10x the maxtemp (it increases gradually...) or slow down the increase (it's a multiplier at --incclean). The cache size has no effect on this (it's not bit-stuffed), but I suggest you don't use so much cache, it doesn't help that much I think.

So this is partially to do with:
* your 10x maxtemp
* your long running time
* your type of problem

Can't do much about it but to lower the temp or lower the incclean. You can also make the available space double what it is now by changing

#define BASE_DATA_TYPE uint32_t

to

#define BASE_DATA_TYPE uint64_t

But I think you'd be _much_ better off setting the incclean lower.

Let me know if the above helped!
