### ISSUE TITLE
Question on removal of command line option --maxdump=xxx

### ISSUE THREAD

**Issue by capiman** [msoos/cryptominisat#386]
With https://github.com/msoos/cryptominisat/commit/b12fbce581c3df2af25238b2183f6ab16fe7c697 the command line option --maxdump=xxx was removed. It is explained in commit 
it is not needed anymore.
Now only all reduceable clauses can be dumped instead a limited set of it.
The output file could get very big.

Is there now some alternative way of doing it? If not, why was it removed? It looks like
having the option in the code has not much dependency on the other, remaining code.

**Comment by msoos** [comment]
It was removed because there are 3 levels of learnt clauses and it just makes no sense to dump them into one place. The saving/reloading is broken and cannot be fixed without massive amount of work. You are more than welcome to do that work, and I will be very happy to merge it in of course! Until then, I do not see the reason why I should work about 2 weeks on something that doesn't help the solver be faster or better at solving regular instances, which is what the solver was created to do.
