### ISSUE TITLE
CMS5 got slower again? Were there bugs which were responsible for the speedup? Ok, better correct and slow, than erronous and fast...

### ISSUE THREAD

**Issue by capiman** [msoos/cryptominisat#387]
Having done a test run with CMS5 around 1 year ago and current version,
it looks like the code got again slower.
(Single threaded run, --maxsol=1000, no other command line options beside --dumpres=6x6.res)
BTW: It was the version compiled by appveyor.
Note: I have not yet tried to compile latest sources on my PC against appveyor version,
which could also be a valuable test to find out the reason.

I took again the 6x6.cnf and searched for the 260 solutions.
Last year's code was able to find solutions in around 4000s (= ~ 66 min),
now it took already around 8000s (= ~ 133 min). 
(Note: not really exactly factor of 2! Slightly smaller).

Were there bugs (I think some of them were fixed in past commits?),
which fixed take longer in runtime than previously? 
Or just because old version was optimized and latest changes are not optimized again?

**Comment by a1880** [comment]
I am not sure if cryptominisat takes the same time for every run, i.e. runs in a deterministic way. There might be random choices which influence the solution time. Have you tried the influence of parameter `--random`?

**Comment by msoos** [comment]
Some things to note:
* CryptoMiniSat has to be fast for a wiiiiide variety of problems
* In order to win at a SAT competition, it has to sacrifice speed on particular problems sometimes
* Current version is non-released, not even alpha, you should be using a published version, 5.0.1

I will run some tests on the wide variety of instances later and will probably tune it. Thanks for the feedback, but I need to change things in it before I can make it better. I will release a version that should be better, hopefully.
