### ISSUE TITLE
[Enhancement] Problem partitioning

### ISSUE THREAD

**Issue by wamserma** [msoos/cryptominisat#388]
After looking around a bit, it seems to me, there is yet no option to give CMS extra guidance on problem solving. To be more specific, it would be nice to say **on the command line** something like _try to solve as far as possible for variables 10000 to 40000 first, then continue with the full problem_.
The reasoning behind this is that I have additional knowledge that is hard to formulate in the CNF, such that for a certain range there might be lot of possible propagation of constants.

Let's take a standard block cypher such as PRESENT or AES as a more concrete example. Verifying a triple of Plaintext, Cyphertext and Key usually is a matter of seconds. Same, when I drop the values for the cyphertext and have CMS recover it. The other way round, when I have CMS recover the plaintext, this can easily take 30 minutes or more. There reason is likely that in the forward case constant propagation matches key scheduling and thus CMS can work through all the clauses pretty well. In the other case values are propagated from "two ends" of the set of equations. Now if I could tell CMS to look at the key schedule variables first, I suspect recovering a plaintext would also be just a matter of seconds.

OF course I could run a script to extract the relevant sub-problem, run a CMS instance on it, put the results back into my original problem and then run CMS on the modified original problem. But this is tedious, error prone and costs extra time for parsing, loading the CNF file etc.

This is mainly about command-line usage and file based inputs but nevertheless I think it is useful when you do not have full freedom in generating your CNF input files or don't want to risk confusing variables when splitting the problem by yourself.

I'm not an expert on SAT solving, this is more from a user persepctive.

**Comment by msoos** [comment]
"The other way round, when I have CMS recover the plaintext" -- so when you give the key and the ciphertext and you want the plaintext, right? Well, it turns out that it wouldn't be a matter of seconds unless you give CryptoMiniSat the *decryption* function instead of the encryption function. The two are not the same, and one needs to reverse a bunch of things (adders sometimes, sometimes other non-linear things) to get there. In fact, I think if I gave you the option to prioritise the variables you think are important,it would most likely be slower. SAT solvers are incredibly good at guessing which variables to branch on. In most scenarios, significantly better than the people who run them. This is because the problem is decomposed and flat to the SAT solver so it can pick any variable it wants and picks the one that conflicts fastest (typically). Hence it will backtrack and fix the variable's value fastest, hence it will solve it the fastest.

Sorry, but every time I added such a feature it:
1) Was useless. People who requested it were baffed how much worse it was than automatic variable picking
2) Hence nobody used it
3) Hence it broke without me noticing
4) Hence it was a maintenance nightmare

Just describe the decryption function instead of the encryption one, and it will take 1 second to run instead of 30 minutes or more :)

Alternatively, you are very welcome to clone the tree, add the functionality, write unit and integration tests for it, extend the fuzzer to test it, log a merge request here and then promise to maintain it in case it breaks due to unrelated changes. It's not a horrible amount of work, but about 2-3 weeks upfront plus about 1week/year maintenance.

Looking forward to the pull request!

**Comment by wamserma** [comment]
Yes, I was aware that reversing some functions would take more time and I was not surprised what I got. I am also not surprised, that this idea had already been pondered and by the experience you detail. I just couldn't find any record of it, so I tried my luck and asked.
Out of curiosity I did a careful experiment with the crypto-setting I took as an example, extracting the key-variables, and getting a solution was a matter of seconds (mainly I/O). I then added the result I got as extra clauses to the full problem. Comparison with direct solution showed 25 minutes vs. 30 minutes.

So, thanks for writing the eye-opener above. Whenever this question comes up again. people can simply be directed to this issue. And don't worry about the pull request -- I'm not gonna waste your time on that. Got enough other projects to wreak havoc on. ;)
