### ISSUE TITLE
build e2cd35f gcc command not built correctly

### ISSUE THREAD

**Issue by baston007** [msoos/cryptominisat#400]
I have just downloaded and attempted to build the latest git image.  See the attached error.txt file for a complete list of messages.  Gcc is looking for "-D_FORTIFY_SOURCE=2" and can't find it.  Within python/setup.py.in I added entry on line 44 to also remove this flag.  Still ne luck.  I missed the comma at the beginning. The flag to remove is ",-D_FORTIFY_SOURCE=2".  This time the build worked.
Rob
[error.txt](https://github.com/msoos/cryptominisat/files/1070003/error.txt)

**Comment by msoos** [comment]
This is due to the new python build. The new setup is better, but has some issues. I'll think about this, but python is pretty crazy :) Thanks, I'll try to work on this. Unfortunately, the comma thing is just not going to work, the underlying problem a lot more complicated than that and it will break other builds if I just do that. 

Thanks for the report!

**Comment by msoos** [comment]
OK, this is related to the other python build issue. I'm closing this, I'll focus on that :)
