### ISSUE TITLE
"greedy unbound" for speeding up finding solutions in bulk

### ISSUE THREAD

**Issue by egri-nagy** [msoos/cryptominisat#421]
Following an off-site discussion, this issue is about the possibility of trying to unbind variables (make them Undef/) such that the solution is still valid, in the context of obtaining a large number of solutions.

**Comment by msoos** [comment]
The expected timeline is possibly next week, most likely the week starting Sept 11. I'm sorry, I'll be on holidays in the coming days! I hope it's not too late until then.

**Comment by egri-nagy** [comment]
No worries. I got very busy (accepted talk for clojure/conj), so it will be
some time before I can return to this problem.
best
@

**Comment by msoos** [comment]
I can't do this... I tried a few times but every time it's a mess because of variable elimination and solution extension. I don't know what to do... I would really need to think about how solution extension can be done with this in mind :S Breaking variable elimination is essentially not an option as it's super-important for speed.

**Comment by egri-nagy** [comment]
I see. Thanks for the effort!
Do you think it is generally true that finding a solution and finding all solutions cannot be optimized at the same time?

**Comment by msoos** [comment]
Well, there are exact counters out there, e.g. sharpSAT if you want to do that :) Or, much-much more interestingly, there is approxMC which is using an old CryptoMiniSat :)

**Comment by msoos** [comment]
I am closing this because exact counters have been improving over the years, for example, we just published work into IJCAI to improve exact counting with SharpSAT. Furthermore, approximate counting has significantly improved over the years. Getting "GreedyUnbound" right is very-very messy and currently I am not even sure it's possible. Hence, I'd rather not attempt doing it. Instead, I'll let exact counters such as SharpSAT and approximate counters such as ApproxMC do the heavy lifting.

I hope this is not too big of a disappointment and I hope you will enjoy using ApproxMC or our improved SharpSAT :) Let me know if you need any help! Cheers,

Mate
