### ISSUE TITLE
Why not use all CPU cores when program running ?

### ISSUE THREAD

**Issue by reza-2018** [msoos/cryptominisat#435]
I have a cnf file with the following specifications
The CNF has 4480 variables in 6800 clauses.
I run it with the following command and only use a CPU core during runtime, and so the speed of execution and response is greatly reduced.

"  cryptominisat5_simple   2_sample.cnf     >    log.txt  "

1. what is the matter? and is it possible that by choosing one of the solver options we are able to use all processor capacities (i.e., all processor cores)?

Another question :
2. How is it possible to get the normal and approximate time to run a Sample with cryptominisat?
For example for my cnf file, It is running for 5 days and has not yet responded.

**Comment by a1880** [comment]
You could try the option "--threads=4" (or another number).
"--help" shows the available options.
Currently, the Windows release is restricted to only a few options.
The Linux release has far more options, many of them suitable for tuning.

It is not possible in general to predict the runtime.
Arbitrary long runtimes do occur in practice.

Cryptominisat is quite fast for many examples.
However, you might want to try other SAT solvers.
Have a look at https://baldur.iti.kit.edu/sat-competition-2017 
for a list of competitive solvers. 
My favorites (not present in the list) include [Z3](https://github.com/Z3Prover/z3) and [Clasp](https://github.com/potassco/clasp). Both offer support for Windows and multi-threading.

**Comment by msoos** [comment]
Actually, if you follow the guide on the README then CryptoMiniSat fully builds on Windows and offers ALL options. Please follow the guide and then you will have more options and the full executable "cryptominisat5" instead of only "cryptominisat5_simple"

The runtime CANNOT be estimated AT ALL. It's like asking for time to go backwards. It cannot.

Using multiple threads makes the runtime and the execution non-deterministic and may increase or decrease the overall runtime. There is a chance that it will help, but not necessarily. Such is SAT solving.

I believe this answers the question so I'm closing. Please re-open if you feel like you have more questions related to this topic.

**Comment by reza-2018** [comment]
Thanks for this guide
Notice that I installed the resolver in the latest version of Ubuntu Linux.
Now with this new setting, all processor cores are used, and so the speed is improving somewhat.
But I still feel that running speed can still be better.

I have been using xor with multiple inputs in my cnf formula and my research area is a cryptosystem analysis and cryptominisat is very good and fast for smaller instances, and I'm sure if I can choose the suitable options for the solver; Solving larger samples will also be good and fast. But I'm a beginner in using solvers. And Please guide me on whether there is a way to improve the speed ? and if so, please propose solutions to improve the speed of the run.

Now, in the file I've shared below, you'll see an instance of the cnf files I'm generating.
https://goo.gl/jvNhyK

thank you
Reza
