### ISSUE TITLE
License

### ISSUE THREAD

**Issue by saraedum** [msoos/cryptominisat#473]
Trying to package this for Debian (#456), I stumbled upon some license question. The `LICENSE.txt` file says that cryptominisat is licensed under MIT (expat).

* [x] There is some code that is licensed under GPL-2 (without the option to upgrade to GPL-3). @msoos is the copyright holder of all this code, so maybe it would be an option to change the copyright headers to use the MIT license instead to make this consistent?
* [x] What is the license of `splncs.bst` and `ieee.cls`?
* [x] Am I right to assume that everything that has no copyright header is MIT licensed (I guess, I can imply that from the `LICENSE.txt` file.)
* [x] `cmake/GetGitRevisionDescription.cmake.in` is BSL-1.0 licensed but as I understand that's fine; cryptominisat can redistribute it under an `MIT` license without any explicit notice.

**Comment by saraedum** [comment]
@msoos: Sorry for this issue. I know that working on licensing is not really productive but Debian is quite picky about these things.

**Comment by msoos** [comment]
It is productive actually (I have worked in industry, I see the value), and I appreciate your work :) Also, please be aware that a MUCH faster version is on the way, so if you could package this, say, the 5th of March, that'd be the best -- the SAT competition deadline is the 1st so of course I shall have a fast solver then, which will get released.

For the individual pieces:
* splncs.bst -- just fixed this one. It now states the license ("This generated file can be redistributed and/or modified under the terms....")
* the only things missing headers should be trivial shell scripts. I am checking for headers for all C and H files and now for the fuzzer and AWS too.
* The python files are under GPLv2, including both the fuzzer and the AWS
* The AWS stuff now is under explicit GPLv2.
* Note that the actual library, headers, etc so stuff that is not for me (e.g. fuzzing with python, performance analysis with AWS) is all MIT and should not be in any other way.

Please let me know what is missing headers! I think all should have them... Should I put them on trivial shell scripts as well? They won't get installed...

As for my rationale:
* Everything needed to build both the library and the binary are MIT. Hence everything that gets installed is MIT. There is absolutely no worry for anyone that their code may be "infected" by GPL.
* All things to do with the python header and package are MIT
* All tests (whether python, C++, or other) are MIT
* Prediction scripts, fuzzing, and AWS are all GPLv2 because I want these things to be in the open. They are stand-alone and need no compilation. They should never be installed or ran on the user's machine, they are for development purposes only.

Please let me know what you think.

**Comment by saraedum** [comment]
@msoos Are you getting the dates wrong somehow? The 5th of March was two weeks ago…

**Comment by msoos** [comment]
Ooops, sorry, I meant 5th of April :)

**Comment by saraedum** [comment]
Great. Thanks for clearing this up. So, I think what's most important is to put basically what you wrote above (non-MIT licensed files are not part of what gets installed/linked against, everything that has no copyright header is MIT licensed) into the `LICENSE.txt` file.

The only remaining issues I see:
* Have you adressed `ieee.cls` already?
* You should consider relicensing the GPLv2 bits under GPLv2+. I think that this avoids problems with redistribution. Assume for example that Sage (*distributed* under GPLv3) includes cryptominisat some day as a standard package. They will then ship a tarball of cryptominisat's sources with Sage. I am not an expert but I know from similar cases that this can be very complicated, lead to lengthy discussions and might require others to produce a tarball that strips everything that is GPLv2 from your repository. I think that it would actually be fine in this case as no works derived from these files are installed but you could possibly shortcut future discussions by going with GPLv2+.

**Comment by msoos** [comment]
Thanks!

The ieee.cls has been fixed. It's basically not relevant, as neither it nor any of its derivatives should definitely not be installed. It's for internal use only. I did put a copyright and a relevant terms of service link to the top, though :)

I remember some issues with GPLv2+ that was non-trivial as well. Some organisations really don't like it. So I prefer GPLv2 or MIT. Everything that's needed to compile or needs to be installed is MIT. So I stick to that if that's OK. If something is deemed needed and must be installed, I'm most likely happy to re-license to MIT. But currently, everything that I know that's needed for it is MIT.

I am now writing a LICENSE file that explains things :)

Do you see any other issues?

**Comment by msoos** [comment]
Ok, there are now even more checks on copyright and I improved the license file :) Let me know if there is anything else to do!

**Comment by saraedum** [comment]
I am surprised, I never heard about anybody having issues with GPLv2+ (and not with GPLv2.) As I understand it, anybody can distribute something that's GPLv2+ under GPLv2…but I am not an expert.

The ieee additions look good.

Would you mind changing the license file to say something like:
```
The general priciple of the licensing is as follows. Everything that's
needed to run/build/install/link the system is MIT licensed. This allows
easy distribution and running of the system everywhere. Files that
have no copyright header are also MIT licensed. Everything else that's
not needed to run/build/install/link is usually GPLv2 licensed or
compatible (see the copyright headers.) The only exceptions are the
following files in docs/:
* `splncs03.bat` which is under the LPPL
* `ieee.cls` which is covered by the IEEE Copyright Policy
```

This makes life easier for packagers. They don't have to dig around in the source to check copyright headers but just have a complete statement at the top of the repository :)

**Comment by msoos** [comment]
OK, done :) The GPLv2+ arises from some industry that are so afraid of GPLv3 that they fire their employees on the spot if they ever even have heard of GPLv3 -- I'm a bit exaggerating but I have seen with my own eyes employees literally fearing for their jobs(!) and wanting to forget ever to have heard of anything to do with GPLv3. It's... extreme. I've seen it, the fear, and it's not fun. So, it stays GPLv2, it's good enough. I understand that those who live and breathe this thing are not afraid of GPLv2+, but that's not who we are targeting -- we are targeting regular employees who don't want to be in any type of awkward situation under any circumstances.

**Comment by saraedum** [comment]
Hehe, ok. You're right, the patenting clauses are "scary" for some people, I guess I am usually thinking about these things from the other perspective.

**Comment by saraedum** [comment]
Great. I think we are in very good shape here :)

**Comment by msoos** [comment]
;) Please wait before pushing this into Debian, though, I need to fix some
performance bugs and release z should be about 2 weeks the deadline of the
SAT competition :)

**Comment by saraedum** [comment]
I just tried to write the `debian/copyright`. There are two files whose copyright/license I could not figure out:
`cmake/FindSqlite3.cmake` (mentions a file containing the "BSD" license but I could not find it anywhere, so which BSD is it?) and `cmake/FindMpiCompilers.cmake` which contains a copyright but no license.

**Comment by saraedum** [comment]
`FindSqlite3.cmake` is probably referring to this BSD license https://github.com/tomahawk-player/tomahawk/blob/master/CMakeModules/COPYING-CMAKE-SCRIPTS. Looks like this file is autogenerated by the cmoduler program.

**Comment by msoos** [comment]
Thanks! Didn't catch those :( Can you please check if this fixed it and if so, close it? Thanks!

**Comment by msoos** [comment]
Thanks, glad it worked :) I probably should release this as 5.6.4? That
would allow it to be tracked in distros as such?

**Comment by saraedum** [comment]
A release would be nice. But maybe you want to wait for a few days so I can see whether anything else is missing for Debian.

**Comment by msoos** [comment]
Surry please do send some feedback :) Thank you again for packaging! I have
lots to learn from your work.
