### ISSUE TITLE
Implement redundant clause query along with a fuzzer that checks them

### ISSUE THREAD

**Issue by capiman** [msoos/cryptominisat#489]
Looking at 
https://github.com/msoos/cryptominisat/commit/7f4081b6ce4648921363ebde9272c97a07ae5414#diff-7ec3c68a81efff79b6ca22ac1f1eabbaL362
I would say dumpred/dumpirred is meanwhile removed.
Is there some replacement to get red and irred clauses after a timed out or partial calculation?

**Comment by msoos** [comment]
OK, it turns out I will implement this feature for a project that needs it and then I will have tests, etc. So things are looking up!

I will rename this feature and then implement :) The fuzzing tests will be a huge pain but they will demonstrate and check that the clauses returned are correct. That is SUPER important. Yaaaay! This feature is coming!!! :D

**Comment by msoos** [comment]
(Note that irredundant clause dumping is already correctly implemented and is available)

**Comment by msoos** [comment]
Done :) Fuzzer, python interface, "--dumpred" the whole lot :)

```
  --dumpred arg                         Dump redundant clauses of gluecut0&1 to
                                        this filename
  --dumpredmax arg (=10000)             When dumping redundant clauses, only 
                                        clauses at most this long
```

Also, the fuzzer now checks that the dumped clauses are correct. Fuzzer running right now :) This is now closed in a way that allows us to make sure it will ALWAYS be correct. Yaaaay!
