### ISSUE TITLE
Command line switch --ml inert?

### ISSUE THREAD

**Issue by jvpeetz** [msoos/cryptominisat#525]
Hi Mate,
seems to me that the switch `--ml` is not utilized any more but is still documented in the online help. Maybe you want to remove that.
Regards,
Jörg.

**Comment by msoos** [comment]
Thanks! I want to keep it in, I am working on it in the devel branch :) It's not ready yet but I'm getting there. In the released code it's pretty useless but it will eventually be useful in the devel branch (it's useless there too for the moment). I am closing because it's a valid issue but the fix is definitely on the agenda and will be released with the newer version, though it might take a few months :) Thanks for reporting! It's valid but I want to keep it this way for a while :)

**Comment by jvpeetz** [comment]
Ah, thanks for the explanation. I'm very curious to see where you're heading to. Would you mind to give some insight or a reference?

**Comment by msoos** [comment]
There'll be an academic paper soon :)
