### ISSUE TITLE
finding all solutions very slow

### ISSUE THREAD

**Issue by janmazak** [msoos/cryptominisat#528]
The method of banning solutions works with reasonable speed only up to about 20 000 solutions (with 100 variables). It gets progressively slower and slower, taking almost half a minute to complete. I tried to compare it to an AllSAT solver http://www.sd.is.uec.ac.jp/toda/code/cnf2obdd.html and it can find all my ~21000 solutions in a fraction of a second. Can something be done about this? It seems that AllSAT solvers are very scarce (not supported by lingeling or glucose?), although I think it would only need a small code modification? (To prove UNSAT the "whole tree" has to be searched anyway?)

**Comment by msoos** [comment]
What you want is model counting. That is a very different problem. Imagine if there are 2^200 solutions. You cannot possibly count them the way you are doing it, or it will take more than the age of the universe. To do that efficiently, either you have to use e.g. an exact counter like sharpSAT or you can use the work that Kuldeep and I have been doing to get approximate counts. If you download CMS 5.0.2 and compile with the `-DUSE_GAUSS=ON` flag then you get a `scalmc` binary. That binary can count the approximate number of solutions over a given set of independent variables that you have to set with

```
c ind var1 var2 ... 0
```

Please see the options to scalmc. If it's not fast enough, then you will have to wait, a new software, a newer scalmc will be released soon once it's published that should help. In the meanwhile, try using this scalmc or sharpSAT. Note that I cannot accept any but reports against that scalmc because I have improved it already but I cannot make it public until it's published :) Good luck!

**Comment by janmazak** [comment]
Well, in my use case I actually have to check each of the solutions to get the result I want (the solutions correspond to perfect matchings in some cubic graphs). Of course, the number of solutions grows at least exponentially, but for graphs with about ~100 vertices the number of solutions is just about 2.5 million (enumerated by bdd mentioned above). The trouble with CMSat is that it has a hard time progressing when the number of banned solutions exceeds a couple tens of thousands (perhaps because there are too many clauses by then).

**Comment by msoos** [comment]
Sorry, CMS was not built to enumerate 2.5million solutions. It could
possibly be made to do that but I suggest you try sharpSAT for that. If
that doesn't work then you probably need to give me some pull requests to
fix the issues as I cannot commit the resources for it. Good luck!
