### ISSUE TITLE
Pre-process INDETERMINATE final state and almost BLANK pre-processed CNF output file

### ISSUE THREAD

**Issue by danieljmg** [msoos/cryptominisat#580]
Hello Msoos,
Im trying to run pre-process following the readme instructions under an updated Windows 10 x64 using your last pre-built non gaussian windows executable. A a SAT solver works flawlessly, but I am having issues with pre-process functionality.

The command:
`cm5.exe -p 1 model.cnf models.cnf`
Returns:
```
...
Wrote solver state to file savedstate.dat and simplified CNF to file models.cnf
s INDETERMINATE

```
However, models.cnf is:
```
p cnf 0 0
c --------- unit clauses
c ------------ vars appearing inverted in cls
c -------- irred bin cls
c -------- irred long cls
c ------------ equivalent literals

```
Independently of the DIMACS input. The rest of the commands as `-p 2` do not obviously work.
Am I missing something?
The CNF model I am testing at the moment is:
```
c 1 a_1
c 2 a_2
c 3 b_1
c 4 b_2
c 5 tseitinvar_1
c 6 tseitinvar_2
p cnf 6 14
-3 5 0
1 5 0
3 -1 -5 0
4 -2 0
-2 5 0
4 5 0
-1 6 0
3 6 0
1 -3 -6 0
2 -4 0
-4 6 0
2 6 0
-1 0
-2 0
```

**Comment by msoos** [comment]
Hey,

Yeah... it does work, but it REALLY simplifies the formula :D If your formula is small, it will remove it entirely. Yep. So... you need a more complicated formula, or it will just destroy that thing.

Beware, the simplifier is made so that if you find a solution to the simplified CNF (in this case, it's trivial, it's an empty CNF), then it will find a solution to the original CNF. However, it does not guarantee model count equality. In other words, if the original formula had 1000 solutions, the simplified formula may only have one. However, if you find that one, it will be able to recover a solution for the original formula -- but only one. Also, if the original formula was UNSAT then the simplified formula will also be UNSAT. So it guarantees SAT->SAT and UNSAT->UNSAT, but does not guarantee equivalent *number* of solutions.

So this is not a glitch -- it's just that the system is very efficient and you need a much harder problem or it will give you an empty formula :) I hope this helped!
