### ISSUE TITLE
Switch between dllexport and import pragmas in public header

### ISSUE THREAD

**Issue by horenmar** [msoos/cryptominisat#595]
Currently, CMSat's public header only uses `__declspec(dllexport)` annotation, which is required to make the class appear in the dll, so a Windows DLL is functional. However, without also providing `__declspec(dllimport)`, every function call pays a performance penalty, because it has to do an extra indirection, see e.g. [this blog post from Microsoft](https://blogs.msdn.microsoft.com/russellk/2005/03/20/lnk4217/).

Since you are already using CMake build, the simplest way of solving it is to use [`GenerateExportHeader`](https://cmake.org/cmake/help/latest/module/GenerateExportHeader.html) to handle it for you.

**Comment by msoos** [comment]
Hi,

I see. Unfortunately, I don't really have time to do this. Could you take a shot at it? It's extremely hard for me because I don't have a Windows installation, so checking if it works is super-difficult for Windows, the feedback loop using the CI in Appveyor is like 15 minutes, so debugging a small issue can take 4-5 hours :( Sorry.

**Comment by horenmar** [comment]
I'll see if I have some free time in December.

**Comment by msoos** [comment]
Thanks! Let me know if you got around to it :)

**Comment by msoos** [comment]
Hey! This should be fixed in the upcoming version, to be released soon :) I am closing because this should be resolved automatically when the new release is out!

**Comment by msoos** [comment]
Thanks again for noticing this and letting me know how to fix :)
