### ISSUE TITLE
Custom branching variable order patch

### ISSUE THREAD

**Issue by mtrimoska** [msoos/cryptominisat#597]
Hello, 

I can not seem to find an option to select a custom branching variable order in the current version of cryptominisat. It seems that there was a patch by Vegard Nossum that allowed to do this simply by adding lines of the form 
b 3 4 17 0
to the cnf input. 

Is there another way to achieve this in cryptominisat5 or is it no longer supported?
Thanks in advance,
Monika

**Comment by msoos** [comment]
Hi,

This is not supported. Mostly because almost everyone who has asked for it were better off by using the standard order :) Also, it's expensive to maintain and there is very little, if any, use for it, given that it most likely will just make things slower. In case you are an expert programmer, and can promise to maintain it for the next 5-10 years, and are willing to contribute the patch yourself, along with all the necessary test cases, I cannot unfortunately merge such a patch at this time :( Sorry!

However, you are almost 100% better off without it -- instead, I suggest you look at how you encoded the problem, and how this encoding be different or improved. Please note that there are entire forests that have been cut down to print research papers on encoding. Look around and you will find many-many :)

Cheers and good luck,

Mate

**Comment by msoos** [comment]
Haven't received a comment, potentially the author may not have the time to write the code, the tests and promise to maintain it for 5-10 years. Closing.

**Comment by mtrimoska** [comment]
Hi,

No problem, just wanted to make sure I'm not missing anything. Thanks for the answer!

Best,
Monika
