### ISSUE TITLE
Max Memory statistics

### ISSUE THREAD

**Issue by vlastikw** [msoos/cryptominisat#629]
The Memory used statistics shows current used memory but the maximum memory can be even 50 % more.

It would be nice to show max memory used statistics, too. It seems that RedL2 is reduced reguraly and therefore takes more memory before reduction than after.

It would be interesting if memory limit reflects max used memory or at some check point only.

**Comment by msoos** [comment]
Hi @vlastikw ,

Thanks for the issue. Can you please let me know how the max memory be queried from Linux, Windows, and Mac in a reliable way? It seems like it could be queried from Linux proc system as per this manpage [here](https://man7.org/linux/man-pages/man5/proc.5.html) using `/proc/[pid]/status`, see `VmHWM: Peak resident set size ("high water mark")`. However, I am reluctant to implement this, because you can get this information very easily:

```
soos@vvv-dejavu:build$ /usr/bin/time --verbose ./cryptominisat5 mytest.cnf  --verb 0
s SATISFIABLE
v -1 2 0
Command exited with non-zero status 10
        Command being timed: "./cryptominisat5 mytest.cnf --verb 0"
        User time (seconds): 0.00
        System time (seconds): 0.00
        Percent of CPU this job got: 92%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.01
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 8820
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 676
        Voluntary context switches: 1
        Involuntary context switches: 2
        Swaps: 0
        File system inputs: 0
        File system outputs: 0
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 10
```

You see, it prints **Maximum resident set size (kbytes): 8820** which is what you wanted, I believe? In the meanwhile, I added comments and marked the information in the `time_mem.h` file, so in case you wanna create a [GitHub pull request](https://linuxhint.com/pull_request_github/), please do so, I would be very happy to review & merge!

Note that under Windows and Mac (i.e. BSD) this is probably a lost cause.

I hope the above helped,

Mate

PS:

**Comment by vlastikw** [comment]
Hi Mate,
I thought something like lingeling does i.e. count memory allocation within app (if max<curr set max) but I assume it could affect performance and needs more coding. I didn't know that it comes from OS statistics. I'm running cryptominisat in linux and I agree that the best for now would be to use/add VmHWM stat. VMpeak might be better if process need to use swap memory and wrote something into swap so it won't be shown under RSS (my observation).

Cheers Vlasta

**Comment by msoos** [comment]
Hey,

Doing what lingeling does is very complicated. It'd take me about 1 month of work to implement that, and it wouldn't bring that much benefit, I'm afraid. In case you feel like doing it, of course, you are more than welcome to do it and create a pull request, however, given the complexity to maintain it, I may decide not to accept such a PR anyway, as maintenance is usually about 80% of the workload, i.e. overall it'd take about 6-8 months of my life over the lifetime of CMS. I'd rather not give up half a year of my life for this requirement, unless there is a really-really good reason for it. If it made the solver 2x fast, I'd do it in a heartbeat, though.

However, please note that even lingeling cannot know how many pages the kernel allocated, and hence max memory the kernel reserved for it, only the kernel knows that. So lingeling is only estimating. In other words, all those months of work wouldn't actually give you a very accurate data. Using `/usr/bin/time` I think is convenient, and, more importantly, *accurate*. Also, it's free! :) 

I'm glad the `/usr/bin/time` works for you,

Mate

**Comment by vlastikw** [comment]
No problem. I definetely understand and agree with you. I just wanted to
share idea with you and thought that you may wish to replace final
statistics with more accurate memory used value (or may be change
description to mem currently used (not max). Anyway it's not worth the
effort if it's not a one liner :-)

Thanks for your feedback anyway, I'm glad that I could share my experience.

Best regards

so 3. 10. 2020 v 15:06 odesílatel Mate Soos <notifications@github.com>
napsal:

**Comment by msoos** [comment]
Ah, I realized you are right. So I now fixed this, it's printing the max mem size now :D See:

```
soos@vvv-dejavu:build$ ./cryptominisat5 mytest.cnf 
c CMS Copyright (C) 2009-2020 Authors of CryptoMiniSat, see AUTHORS file
c CMS SHA revision 7ef15ad94dc6665bf70b08d66c635dd62251ee0d
[...]
c Conflicts in UIP         : 0           (0.00      confl/time_this_thread)
c Max Memory (rss) used    : 8348 kB     
c Total time (this thread) : 0.02        
s SATISFIABLE
v -1 2 0
Command exited with non-zero status 10
        Command being timed: "./cryptominisat5 mytest.cnf"
        User time (seconds): 0.02
        System time (seconds): 0.00
        Percent of CPU this job got: 100%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.02
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 8724
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 672
        Voluntary context switches: 1
        Involuntary context switches: 1
        Swaps: 0
        File system inputs: 0
        File system outputs: 0
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 10
```

Note that it's actually kernel-dependent how that's formatted, so it's printing kB for me... may print something else for you. In case the kernel doesn't support this, it should fall back to the old stuff :) *Thanks for the questions and responses, it was good to question this decision and I'm glad I could fix the issue!*

PS: the difference between 8724 and 8348 is due to the cleanup needing memory, which we cannot catch at that point.
