### ISSUE TITLE
A simple question regarding ordering in a SAT solution?

### ISSUE THREAD

**Issue by sagarAI** [msoos/cryptominisat#644]
Whenever I print a SAT solution from cryptominisat, I always see the literals to be ordered w.r.t to their absolute values. I just wanted to confirm if this behaviour is guaranteed from the solver ?
I am asking this as I need to generate all solutions in this fashion for my application and calling a sort function on them will be quite time expensive .

**Comment by msoos** [comment]
Hi,

They are not guaranteed to be ordered. It's not a good idea to depend on them being ordered, because you may want to use another SAT solver another time, or another version of CryptoMiniSat another time, that may not have these variables ordered. 

Note that calling `sort` should be incredibly fast, especially in comparison to how much time it takes to run a solver. If `sort` is slower than `solve` then maybe there is something wrong with the `sort` function  you are using -- check it for some issues :) Make sure you use an `O(n*log(n))` sort function such as quicksort! 

I hope the above helped,

Mate
