### ISSUE TITLE
Explanation of the error information

### ISSUE THREAD

**Issue by xiaohuangthu** [msoos/cryptominisat#646]
Hi,
I saw the following error information several times when I was running with your solver. Could you please explain me what the result is to see this error? Is it because of lack of memory?

foo-sat: /home/cryptominisat/src/searcher.cpp:1242: CMSat::lbool CMSat::Searcher::search(): Assertion `ok' failed.
/var/lib/slurm-llnl/slurmd/job05926/slurm_script: line 9: 26179 Aborted                 ./foo-sat

Best,
Senyang

**Comment by msoos** [comment]
Hi,

Potentially, there is a bug in CryptoMiniSat, or there is a bug in the way you are using it. You'll need to use `gdb` and try to get to the bottom of it. In particular, calling `add_clause()` after the system is in UNSAT mode leads to this error. So please debug your system, and if the issue is not with the use of CryptoMiniSat, but CryptoMiniSat itself, then please paste here the backtrace and some explanation so I can debug!

Looking forward to fixing in case it's a bug with CryptoMiniSat,

Mate

**Comment by msoos** [comment]
Sorry, but I cannot debug this unfortunately. I need to close, because there is too little information here to be able to fix. You can re-open this issue, of course, but please send in the CNF file that is causing the error to occur. Thanks!
