### ISSUE TITLE
Is incremental simplification possible?

### ISSUE THREAD

**Issue by MingweiSamuel** [msoos/cryptominisat#655]
Is setting a timeout while simplifying possible? It seems it is not possible to determine when simplification is complete VS when a timeout has been triggered (unless SAT/UNSAT is found).

**Comment by msoos** [comment]
Hey!

For both `--preproc` and for the simplifications, there are timeouts, but they are NOT timeouts in terms of time, but in terms of operations. This allows the preprocessor to be deterministic. You can adjust this operation limit by setting e.g. `-m 100` which will set the timeout multiplier to 100, instead of the default 3, making it 33x longer. You can also set `-m 0.1` which will set the timeout multiplier to 0.1, instead of 3, making it 30x shorter.

I hope this helped. If not, please let me know and I can try to help more :) Cheers,

Mate

PS: Time-based timeouts are not useful, because it means that it's impossible to reproduce your results or debug your code. Hence, I use deterministic timeouts through counters, that have limits, which you can adjust with `-m X`.

**Comment by MingweiSamuel** [comment]
Thanks Mate,

I guess I need to ask, what exactly does simplification do? (Is it different from preprocessing?) I thought it finds and removes predetermined variables & redundant clauses, but I realize I don't actually know, and it doesn't seem to match what I've been seeing while playing with it.

For our practical purposes I made this issue because we'd like to be able to yield to the javascript event loop on a schedule, so we can interrupt computation, but there are other ways to have emscripten to do that I think.

**Comment by msoos** [comment]
Ah, okay. So simplification does a lot of things, at least 20+ and I can't really explain it all here, I'd need a book for that. Here is the list:

```
           "scc-vrepl,"
            "sub-impl,"
            "intree-probe,"
            "sub-str-cls-with-bin,distill-cls,distill-bins,"
            "scc-vrepl,sub-impl,str-impl,sub-impl,"
            "breakid,"
            //occurrence based
            "occ-backw-sub-str,occ-clean-implicit,occ-bve,"//occ-gates,"
            "occ-bva,occ-ternary-res,occ-xor,card-find,"
            //consolidate after OCC
            "cl-consolidate,"
            //strengthen again
            "str-impl,sub-str-cls-with-bin,distill-cls,distill-bins,"
            "scc-vrepl,"
            //renumber then it's time for SLS
            "renumber,"
            "sub-impl,"
            "bosphorus,"
            "louvain-comms,"
            "sls,lucky"
```

Sorry, I really can't help you with all of them, it'd really require a book. You can read some research papers and read the code, through. They are all time-outed as per above, i.e. operation-outed and they all try to simplify the problem (except SLS which tries to solve it). Here, "simplify" may even mean adding variables (BVA), eliminating variables (BVE), and very large list of other things. It's always incremental in the sense that you can run it again and it will do something, as we almost never run these to fixedpoint.

I hope this helped,

Mate

**Comment by MingweiSamuel** [comment]
Thanks Mate! This is very helpful for me and I appreciate it.
