### ISSUE TITLE
Continuation of #652 - Now OOM-Killer gets activated...

### ISSUE THREAD

**Issue by capiman** [msoos/cryptominisat#657]
After fixing error in #652 I am now able to find a lot more solutions:
Instead of 62611 solutions (without the fix), I am now able to find 106948 solutions.
But then OOM-Killer kills my task. I have seen it multiple times during testing my fix for #652,
but thought, it comes from running to much test tasks at the same time.
Then I freed a lot memory and ran it again. I saw when it was using around 34 Gbytes,
and suddenly it stopped. No clue!

Then I searched and used the following

while true ; do ps -e -orss=,args= | sort -b -k1,1n | grep again | grep e2 | grep -v tail >> logme_again_again.log ; tail -n 1 logme_again_again.log ; sleep 1 ; done

to collect and log memory consumption of my task each second. Here is a picture of it:

![Memory-Consumption-of-cryptominisat-issue-652](https://user-images.githubusercontent.com/2673562/128741846-5ec0c92d-b2fa-4d96-8593-292686b36158.png)

X-axis is runtime in seconds. Test run tooks almost 2 hours.
From time to time there is a big spike. But I see "strategy token" output only in first 543 lines,
nothing more in remaining 856729 lines.
Each spike is around 10s long.
Last spike goes from 34 Gbytes (!) to 54 Gbytes, which is too much for my system, so OOM-Killer gets activated.

**Comment by capiman** [comment]
[logme_again_again.log](https://github.com/msoos/cryptominisat/files/6956082/logme_again_again.log)

[e2_new_2021_only_ring_0_and_ring_1_and_ring_2_202108020807_test_again_again.zip](https://github.com/msoos/cryptominisat/files/6956093/e2_new_2021_only_ring_0_and_ring_1_and_ring_2_202108020807_test_again_again.zip)

**Comment by msoos** [comment]
Hi,

The doubling of the memory usage is due to the reallocation of memory during `consolidate()` in clauseallocator.cpp. This *could* be done without doubling of memory, but someone would need to write that code. So this is really an improvement opportunity. I would be happy if you did the work, but it's not as straighforward as it seems. Re-ordering the clauses in the allocation to match that of the watchlist gives ~10% improvement. Doing a `realloc()` with a compression and a linear pass would go around the doubling of memory issue, however, it would also lose the 10% speed bump.

If you could write code that does both, and e.g. uses the non-doubling when the memory usage is more than e.g. 5GB, that would be cool, actually! Then we'd have the right trade-off. Sorry, I don't have the time to do that right now :(

I hope this helped,

Mate

**Comment by capiman** [comment]
Closed due to

https://github.com/msoos/cryptominisat/issues/649#issuecomment-917955379
