### ISSUE TITLE
ERROR: while reallocating clause space

### ISSUE THREAD

**Issue by ultramaga** [msoos/cryptominisat#681]
Hi msoos,

Enclosed find the Crypotminisat5 output from my cnf input.  My pc only has 4Gb of ram, could this be the problem?  Please offer any advise based on the output.
[results_cryptominisat5.txt](https://github.com/msoos/cryptominisat/files/8709323/results_cryptominisat5.txt)

Thank you for looking.
mike

**Comment by msoos** [comment]
Hi,

You are using 102 million clauses. My guess is that you may want to change the encoding that you are using. It is possibly too verbose. There are likely other encodings that perhaps use more variables, but use way less clauses. I see that you are using only 141k variables. That's extremely low compared to 102M clauses. I suggest using encodings that are less verbose, perhaps by using more variables. SAT solvers will likely not be efficient on these types of extremely verbose formulas. I suggest aiming for less than 10 million, optimally less than 1 million clauses. Please check out some encoding papers, or e.g. use an SMT solver to encode your problem to SAT, which should make it less verbose.

Unfortunately, 4GB is very low. You need much more memory if you have such large formulas. But again, I would concentrate on improving your encoding.

Closing, because there is nothing I can do to improve the situation, 4GB of RAM is very low for a 100M clause problem.

Mate

PS: you can try using [kissat](https://github.com/arminbiere/kissat) but again, your _encoding_ is likely incorrect. You need to fix your encoding, and it may solve 1000s of times faster, and you will need a lot less memory.

**Comment by ultramaga** [comment]
Thank you Mate!
