### ISSUE TITLE
M1 Mac cannot compile 

### ISSUE THREAD

**Issue by liyu0x** [msoos/cryptominisat#689]
Hi, I use M1 mac to compile this, but it go to failure.

```
In file included from /Users/yuli/Documents/GitHub/cryptominisat/src/searcher.h:30:
/Users/yuli/Documents/GitHub/cryptominisat/src/time_mem.h:204:66: warning: unused parameter 'max_mem_usage' [-Wunused-parameter]
static inline size_t memUsedTotal(double& vm_usage, std::string* max_mem_usage = NULL)
                                                                 ^
3 warnings generated.
[ 82%] Linking CXX shared library ../lib/libcryptominisat5.dylib
Undefined symbols for architecture arm64:
  "CMSat::SQLiteStats::SQLiteStats(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      CMSat::Solver::set_sqlite(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) in solver.cpp.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libcryptominisat5.5.11.dylib] Error 1
make[1]: *** [cmsat5-src/CMakeFiles/cryptominisat5.dir/all] Error 2
make: *** [all] Error 2
```

And I use commond 'arch -x86_64 zsh', still failure.

**Comment by msoos** [comment]
Thanks for reporting! Can you please pull and try to build again? I am really surprised of this, but it should be fine now, unless you want to build with `-DSTATS=ON`, which I am assuming you are not. If it still fails, please:

* delete the `build` folder
* `mkdir build && cd build`
* Build with cmake and make

And give the all of the above output, including cmake, make etc outputs.

I hope I have fixed it, otherwise, looking forward to the outputs so I can fix :) Thanks,

Mate

**Comment by liyu0x** [comment]
Ok, Fine!

Thank you!

**Comment by msoos** [comment]
Thanks for the feedback. Can you please close the issue? Thanks!
