### ISSUE TITLE
CMAKE Generator

### ISSUE THREAD

**Issue by a1880** [msoos/cryptominisat#695]
Hi Mate,

The CMAKE generator for Visual Studio 17 needs to be changed to repair the AppVeyor script:

`cmake -G "Visual Studio 17 2022" -A x64`

Previous versions did not need the -A parameter.

Greetings,

Axel

**Comment by msoos** [comment]
HI Axel,

Given that [The Windows Subsystem for Linux (WSL)](https://learn.microsoft.com/en-us/windows/wsl/install) is so easy to set up and run, should we work on having a Windows executable? The Windows build been broken for a long while, and currently it's broken again, due to some boost issue. Besides, all the interesting work is nowadays done on Arjun, ApproxMC, UniGen, and GANAK, and not on CryptoMiniSat -- but none of those project compile on Windows. I'd suggest using a WSL setup that will comfortable compile all of these tools very easily. What do you think?

Mate

**Comment by a1880** [comment]
Installation of WSL is easy and [well documented](https://learn.microsoft.com/en-us/windows/wsl/). Git download and build work flawlessly for CryptoMinisat, Arjun und Louvain_Communities.
To execute the resulting binary from Windows, one has to use the Windows wsl.exe command. It is not possible (afaik) to copy and use the binaries outside WSL standalone.

So, pressure is reduced to provide Windows binaries.

I have to figure out, how different text linebreak conventions are handled. It would also be interesting to compare the resulting tool performance.

**Comment by msoos** [comment]
Ah, cool, glad to hear it works! Yeah, WSL is relatively easy to use, but indeed, the end-of-line convention may be slightly upset. Overall, I'm glad to hear it works :)

Mate

**Comment by msoos** [comment]
I have removed AppVeyor completely. I know this is not ideal, but WSL is pretty good and many people use it. So I think it's OK. I'm closing this issue, because I plan to support WSL only if that's OK.
