### ISSUE TITLE
Pycryptosat versioning number, when compiling the python wrapper with LARGEMEM=ON

### ISSUE THREAD

**Issue by stegua** [msoos/cryptominisat#696]
Dear developers,
there is a issue in the python wrapper when printing the library version:

```
python3 -c "import pycryptosat; print(pycryptosat.__version__)"
```

which prints:

```
${CMS_FULL_VERSION}
```

However, I discovered this while trying to compile the python wrapper with the LARGEMEM option set to ON.
In the end, the compilation process was successful, but I have no means to understand which version of pycryptosat I am using.

Thanks for your support.
Bests

**Comment by msoos** [comment]
Hi,

Wow, good catch! Thanks! I just fixed the issue with the version, yay :) I'll update the pypi package soon -- because we have one now, yay! Here: https://pypi.org/project/pycryptosat/

However, I don't know how to support LARGEME as part of the python module that's PIP-installed...  I'd have to maintain 2 pypi modules, say, `pycryptosat` and `pycryptosatlargemem`, right? The way pypi works makes it very hard to do anything else I think... I am not a pro at pypi, though. I'd be possible to do it locally: just add `("LARGEMEM", "ON")` here: https://github.com/msoos/cryptominisat/blob/master/setup.py#L100

If you can make a PR that allows that to be added as part of some command line parameter to `python setup.py build` then I'd be happy to merge it. What do you think?

**Comment by stegua** [comment]
Thanks Mate for the fast fixing.

However, I don't know how to support LARGEME as part of the python module
> that's PIP-installed... I'd have to maintain 2 pypi modules, say,
> pycryptosat and pycryptosatlargemem, right?
>
I suppose the adding a note somewhere in there README.md fille will be more
than enough.


>  I'd be possible to do it locally: just add ("LARGEMEM", "ON")
>
I tried, but this did not work. because those macros are intended for CMAKE.
I fix it by modifying the setup.py file by manually adding the flag
'-DLARGE_OFFSETS' as follows:

extra_compile_args = ['-I../', '-Isrc/', '-std=c++17', '-DLARGE_OFFSETS'],

Let me think what is about the best option in this case, and then I will do
a PR.

Thanks again for this nice solver and for your quick response.

**Comment by msoos** [comment]
Hi,

I looked around, and I am not sure you can actually add any options to setup.py that's standard that would allow to change things like that. So I think it needs to be a manual process, just like you did. pip is not great in some ways. I have now added information in the `README.md` under `python/`, so what you did is documented.

I hope this helps,

Mate
