### ISSUE TITLE
Cryptominisat general questions

### ISSUE THREAD

**Issue by amatuag** [msoos/cryptominisat#699]
I had emailed you, but you suggested I ask here via an issue so here goes. 

I have to compile **without Cmake** as I have to use an internal build system at work so I am trying to see if I can simplify the source tree and remove files I don't need (e.g the msvc folder). 

Q1. What are picosat and Oracle used for in the latest Cryptominisat ? We had a really old version of your solver (2009) which seemed to be just minisat + XOR reasoning. I also see that you have added some SQL support to collect stats.

Q2. I mostly am working on circuitSAT problems where I sometimes have a lot of XOR gates chained together. Does your xorfinder.* try to identify CNF clauses generated by gates of the form o = XOR (a,b) and then model them as a conjunction of XOR clauses to solve using Gaussian elimination ?

-Sid

**Comment by msoos** [comment]
Hi,

Thanks for the issue! Let me respond below :)

Q1. The difference between CMS in 2009 and now is about 40k lines of code. I can't explain that here :) But the difference is a lot more than SQL. Actually, SQL doesn't even get compiled in by default. The main differences are all-levels GJ elimination, better inprocessing and better heuristics.

Q2. Yes, it will discover XOR constraints that are encoded into CNF, and then will put them in a big matrix and perform Gauss-Jordan elimination on it on-the-fly, at the same time as the CNF is being solved, at every level of the search tree. In other words, it won't just run GJ at toplevel, but at every level. The system will, however, check if GJ is really helping, and if not, it will turn it off. Just because there is a matrix, unfortunately it doesn't automatically mean it helps :(

Note that if this is for work, then I of course expect the employer to either (1) make your work open-source, at which point I am hapy to help in case that helps CryptoMiniSat to be better (note: making it work for an in-house build system doesn't in general help CMS), or (2) if it's not open source, then of course while I am happy to merge in PRs that you create, I cannot of course do work, since my time is valuable. However, I'd be very happy to merge in PRs that e.g. improve performance or usability, or fix bugs that you discover while using the system, etc!

I hope the above helped,

Mate

**Comment by amatuag** [comment]
Hi Mate,

Thanks that helps.

This work won't be open source and my desire is to not modify CMS unless I find an obvious bug or performance issue. If I do, I will make a PR and hopefully justify its value. I will try to also share representative CNFs highlighting the problem if I can.

-Sid
