### ISSUE TITLE
XOR gates to XOR clauses

### ISSUE THREAD

**Issue by amatuag** [msoos/cryptominisat#700]
Hi Mate,

I apologize if this is too basic a question, but I mainly work in circuitSAT.

If I have a constraint such as c = XOR(a,b) coming from a XOR gate, I will normally encode this via the Tsetin transform into 
(~c+~a+~b)(~c+a+b)(c+~a+b)(c+a+~b). Each XOR gate in my circuit would add 4 clauses to the problem.

I know cryptominisat has an XOR finding class to identify these XOR constraints, but would it be more efficient instead to instead add the above constraint as an XOR clause directly to solver, i.e., XOR(~a,~b,~c) so cryptominisat doesn't have to find it.

I hope I got my math right but ( c = XOR(a,b) ) should be the same as XOR(~a,~b,~c)

Thanks

**Comment by msoos** [comment]
Hi,

`
I know cryptominisat has an XOR finding class to identify these XOR constraints, but would it be more efficient instead to instead add the above constraint as an XOR clause directly to solver, i.e., XOR(~a,~b,~c) so cryptominisat doesn't have to find it.
`

This is currently kinda incorrect -- CryptoMiniSat actually will translate the XOR constraint you put in the DIMACS input with (`x ... 0) into these clauses, then re-discover this XOR, again from the CNF. This is explained in https://meelgroup.github.io/publication/aaai19_bird/ (presentation: https://meelgroup.github.io/files/slides/AAAI19_BIRD.pdf). However, if you put it in as an XOR constraint, you won't have to wait for CMS to discover the XOR (i.e. reconstruct it). Otherwise, your explanation is good. The input format is that:

```
x 1 0
```

Means `XOR (1) == TRUE`, i.e. `var1` has to be `TRUE`. So e.g.

```
x 1 2 0
```

Means `XOR (1, 2) == TRUE`, i.e. `var1` has to be the opposite of `var2`.

The advantage of using CryptoMiniSat is that it will discover these XOR constraints from the CNF (or you can add them via `x ... 0` directly) and it will automatically use them to run Gauss-Jordan elimination at all levels (once it discovered them, pretty quickly, but you can force this with `--presimp 1`). If this is not helping your system, then e.g. `kissat` would also work well, potentially faster. However, if  you have many XORs and they interact a lot, then `kissat` will completely fail (as it's exponential for it, and I don't mean exponential how it's used in the colloquial, I mean exponential in math terms, so ~25 variables and it runs for weeks, 40 variables and you need to wait until the Sun becomes a white dwarf).

I hope the above helped.

Mate

**Comment by amatuag** [comment]
That helps. Yes, I may potentially have many XORs that re chained together. 

I am planning to do this in C++ directly.  Is this the right C++ API ?   Could you please explain why this API doesn't simply accept a vector of lits (say I want to add XOR (1,-2) via the API) ?

`bool add_xor_clause(const std::vector<unsigned>& vars, bool rhs);`

**Comment by msoos** [comment]
Yep, that's the right API! You add a set of variables, and the right-hand-side (i.e. = TRUE, or = FALSE).

Good luck,

Mate

**Comment by amatuag** [comment]
Thanks. I just came across this https://www.msoos.org/xor-clauses/

**Comment by amatuag** [comment]
I generated some random XOR heavy CNFs. I noticed that despite having interacting XOR clauses, Kissat was significantly faster. I even tried --presimp 1. 
[test_xors.cnf.txt](https://github.com/msoos/cryptominisat/files/10129933/test_xors.cnf.txt)

This is an example CNF. Do you expect cmsat to perform better on examples such as this ?
