### ISSUE TITLE
cryptominisat v5.5

### ISSUE THREAD

**Issue by maliabd-al-majid** [msoos/cryptominisat#702]
Hi,

I am currently using an old version of cryptominisat 5.5 which uses libcryptominisat5.so.5.5. however, when i installed the newest version of cryptominisat and I got an error: 

>  error while loading shared libraries: libcryptominisat5.so.5.5: cannot open shared object file: No such file or directory

So i would like to ask, where i can find libcryptominisat5.so.5.5. 

i checked the previous versions, but i couldn't find version 5.5

Thanks in advance.

**Comment by msoos** [comment]
Hi,

You are likely still using the old executable. Issue `which cryptominisat`, and delete the file that it points you to. It will likely work then. You likely have 2 CryptoMiniSats installed, but the old one has only the library installed. So you need to delete the old binary, and then the new binary will be the default and work.

In general this has little to do with CryptoMiniSat. It's an issue with the way you are using your Linux system. You can use the static binary that's here: https://github.com/msoos/cryptominisat/releases It will then surely work. Please google about library locations in Linux (e.g. `/usr/lib/` and /usr/local/lib`) and binary locations (`/usr/bin`, `/usr/local/bin`) and learn a bit about how programs can be fully deleted (you have to delete both the library and the binary).

Again, I STRONGLY suggest you use the static binaries that are attached with the releases, as per my link above. That will "just work" and you won't have any issues with it. Unfortunately, I can't help you much because this has nothing to do with CryptoMiniSat, it's the way you are using Linux. Again please use the static binary.

I am closing because I can't help much here. If you have further issues on using CryptoMiniSat on Linux regarding libraries/binary issues, I suggest going to an IRC/Telegram/Matrix channel where you can get hands-on help. I do this sometimes, but doing it through this GitHub interface, rather than an online chat is VERY hard, VERY slow, and would frustrate both of us :D Instead, just ask on a Linux chat system, there are usually people there, like me, who can help.

If you have issues with CryptoMiniSat, such as wrong results, crashing on a CNF file, of feature requests etc. I am of course happy to help over GitHub.

Good luck,

Mate
