### ISSUE TITLE
Parallelisation support of CMS

### ISSUE THREAD

**Issue by Gy-Hu** [msoos/cryptominisat#703]
Hi, I want to know if there is any parallelization support for CMS. What I need is solving multiple SAT problems at the same time **（NOT multi-threading solve the one CNF formula)**

Thanks

**Comment by capiman** [comment]
Hi! Just calling CMS multiple times?

**Comment by msoos** [comment]
Yep, from e.g. a system that supports job batching. You can even do it via
Bash.

Cheers,

Mate

**Comment by Gy-Hu** [comment]
Thanks for reply! @capiman  and @msoos .

What I actually want to do is to call multiple CMS in an existing C++ program and feed them different SAT problems to solve simultaneously (so basically I am not asking if I have multiple cnf in my folder, how to call cms to solve them at the sam time). Is it possible to use <pthread.h> to apply this? or if there exists any good method?

**Comment by msoos** [comment]
Yes. However, this is not a CryptoMiniSat question. This is to do with C++, threading, etc. Please check out https://www.tutorialspoint.com/multithreading-in-cplusplus or search for `multi threading in C++ howto`. I cannot help with this because this really depends on your problem, your context, etc. and has nothing to do with CryptoMiniSat. CryptoMiniSat can be used in this way, but you will need to figure out how you want to do it exactly.

Good luck, and do try to find an IRC channel/discord channel for C++ in case you are lost, they tend to be pretty nice over there, and can help you debug. Cheers,

Mate
