### ISSUE TITLE
Core dump on command line parameter error

### ISSUE THREAD

**Issue by capiman** [msoos/cryptominisat#705]
```
$ ../cryptominisat-20221226/build/cryptominisat5 --distill=0 --distill=0
terminate called after throwing an instance of 'boost::wrapexcept<boost::program_options::multiple_occurrences>'
  what():  option '--distill' cannot be specified more than once
Aborted (core dumped)
$ ../cryptominisat-20221226/build/cryptominisat5 --bva=0 --bva=0
terminate called after throwing an instance of 'boost::wrapexcept<boost::program_options::multiple_occurrences>'
  what():  option '--bva' cannot be specified more than once
Aborted (core dumped)
$
```

**Comment by msoos** [comment]
Hi,

While this is not ideal, it does tell the user that the command line is broken. It probably shouldn't core dump but it clearly and very visibly shows what the error is, and explains it in detail. This is already 100x better than most other SAT solvers, or indeed almost any research tool.

I am closing because it's not critical to the functioning of the system. However, I'd be happy to review a Pull Request and merge it if you feel like fixing it up!

Sorry, I have very little time to do things nowadays, I need to work on my job instead,

Mate

**Comment by capiman** [comment]
This perhaps fixes the error:

https://github.com/msoos/cryptominisat/pull/707

**Comment by msoos** [comment]
Thanks, merged!
