### ISSUE TITLE
preproc option does not work

### ISSUE THREAD

**Issue by ale-depi** [msoos/cryptominisat#711]
Hi @msoos 

I have used `--preproc` option until 5.8.0 version but it seems that it does not work in 5.11.4 release and 5.11.7 (actually the master). Running `cryptominisat5 --preproc 1 sat-cnf.txt sat-simp-cnf.txt` (or even using `-p1`), I respectively have:

- 5.11.4:
```
terminate called after throwing an instance of 'boost::wrapexcept<boost::program_options::unknown_option>'
  what():  unrecognised option '-p1'
Aborted (core dumped)
```

- 5.11.7:
```
Error: unrecognised option '--preproc'
```

I attach the Dockerfile I use (very minimal) and the (dummy) CNF. (Sorry for the `txt` extension but GitHub does not allow many files format.) In the Dockerfile, you can see both methods I use to install the aforementioned versions of CryptoMiniSat.
[sat-cnf.txt](https://github.com/msoos/cryptominisat/files/10841097/sat-cnf.txt)
[Dockerfile.txt](https://github.com/msoos/cryptominisat/files/10841116/Dockerfile.txt)

Alessandro

**Comment by msoos** [comment]
OOops, thanks for reminding me! Yes, preprocessing has been moved to our tool [Arjun](https://github.com/meelgroup/arjun). However, it doesn't have feature parity yet, sorry. Basically, the preprocessing was not as good as I wanted it to be. The preprocessing in Arjun is waaaaay ahead of what we had here.

Unfortunately, Arjun currently doesn't have feature parity. In particular, if you find a solution in the simplified formula emitted by Arjun, we don't yet have a way of mapping it back to a solution in the original CNF. This is actually not that hard to do. However, we currently don't support it in Arjun. It is actually needed for some uses of Arjun, in particular, for generating uniform solutions. So we should have it. Can you please open an issue for Arjun to state that we need a way to map back solutions? Then I'll work on it in the coming weeks. Please also refer to this issue here so it's all linked together.

In the meanwhile, I believe this issue can be closed -- there is no plan to support preprocessing as part of CryptoMiniSat, only as part of Arjun. This is the right way to do it, i.e. to use CMS as a library, and not a something that has everything and the kitchen sink built right into it :D This should make sure that we concentrate knowledge and know-how in separate tools, so each tool can be good at a single thing :)

Let me know what you think,

Mate

**Comment by msoos** [comment]
NOTE: I have pushed b4ba4bfbac11b8cb4dcea766096b00ce59dfb940 and bd2b169e6e5bb05c8370901b8247c756b01c75f7 to update the readme and the code to reflect that preprocessing has been removed.

**Comment by ale-depi** [comment]
First of all thank you for the fast reply.

Perfect! Indeed, I wanted to suggest to remove from README the preprocessing usage which could be misleading since it does not exist anymore.

The idea is great. A specific tool for every task is noble since everyone can contribute with the best of his/her knowledge, but I think that sometimes a swiss-knife can be useful because one coming from other fields (cryptography as me, finance, medicine, ...) needs just the best SAT solver implementation to solve a part of its problem. Thus, an orchestrator for CMS, Arjun, Louvain Community Detection, ... could be appreciated as well.

Yes, I can. I am scared to do that because I guess it is already a part of the TODOs for the Arjun project and I do not see the point for opening the issue. Anyway, since the request comes directly from you, Mate, I will do that. (I do not know how to refer to this issue but I guess I will discover it.)

I totally agree. This issue is meaningless since your explanation and can be closed. Will you do that?

Thank you

Alessandro

**Comment by msoos** [comment]
Cool, thanks, yeah, I'm closing this and will work on the Arjun issue in the coming weeks :) Thanks for opening it!

Cheers,

Mate
