### ISSUE TITLE
Unexplainable behavior on a SAT instance

### ISSUE THREAD

**Issue by kix6lj** [msoos/cryptominisat#723]
Hi,

I've run cryptominisat-5.11.11 release on a satisfiable CNF and it doesn't terminate in 1000s. However, after I changed the header from
`p cnf 7313 21850` to `p cnf 7314 21850` without changing anything else (and there're exactly 7313 variables in  the CNF). The solution was found within 15s.

The CNF is here [1.cnf.txt](https://github.com/msoos/cryptominisat/files/11915778/1.cnf.txt). I've tested it on version 5.11.11 with default parameters. Hope you can reproduce it.

I wonder why it affects the searching strategy of cryptominisat.

**Comment by msoos** [comment]
This is because it's a very easily satisfiable instance when running a local search solver. I recommend using YalSAT: http://fmv.jku.at/yalsat/ It finds a solution in 1.29s. These kind of instances can behave erratically with CDCL SAT solvers. Modern SAT solvers, like CryptoMiniSat try to remedy this by using a local search solver sometimes. However, it's not perfect.

For your kind of instances, I'd suggest using a local search solver such as YalSAT.

I hope the above helps,

Mate
