### ISSUE TITLE
IPASIR usage documentation

### ISSUE THREAD

**Issue by MikolasJanota** [msoos/cryptominisat#726]
Please add documentation how to use the solver with IPASIR.

**Comment by MikolasJanota** [comment]
I had found that :) But somehow I'm having trouble using it. Shouldn't the following work? (Compile with `g++ foo.cpp -lipasircryptominisat5`). BTW many error appear if I try to compile as C.

```
#include<iostream>
const char * ipasir_signature ();
int main() {  std::cout << ipasir_signature() << std::endl;  return 0; }
```

**Comment by msoos** [comment]
It builds an example for you and runs it. Please build with `-DENABLE_TESTING=ON` along with `-DIPASIR`. It will then build `ipasir_example`:

```
$ cd build
$ ./tests/ipasir_example
signaure: cryptominisat-5.11.11
```

I have now put the signature `printf` there, just for the kicks but it worked and still works flawlessly.

IPASIR is C so you need to build with a C compiler, or you need to declare it with extern C, please see [this post](https://stackoverflow.com/questions/1041866/what-is-the-effect-of-extern-c-in-c). I wrote a trivial file and it worked out-of-the-box:

```
$ cat tmp.c
#include "stdio.h"

const char * ipasir_signature ();
int main() {
    printf("%s\n", ipasir_signature());
    return 0;
}
```

Works right out of the box, the gcc command line is:

```
gcc tmp.c -lipasircryptominisat5 -o stuff
```

Then you can run it with 

```
./stuff
```

I have now tried all combinations of builds etc, and it works every time, all the time, flawlessly. Please build with gcc, or use `extern C` as per that stack exchange post.

I hope this helps!

**Comment by MikolasJanota** [comment]
You're right, I was missing `extern` in C++. However, I'm still unable to build it in C. Anyhow, I just wrote a wrapper, while ignoring ipasir, which is probably a better way anyhow. If this is at all useful, this is how I download and compile.

```
#!/bin/bash

foo () {
cat <<EOF
#include<stdio.h>
const char * ipasir_signature ();
int main() { printf("%s\n", ipasir_signature()); return 0; }
EOF
}
foocc () {
cat <<EOF
extern "C"
{
const char * ipasir_signature ();
}
#include<stdio.h>
int main() { printf("%s\n", ipasir_signature()); return 0; }
EOF
}

CMSFLAGS="-DONLY_SIMPLE=ON -DNOZLIB=ON -DSTATS=OFF -DNOVALGRIND=ON -DENABLE_TESTING=OFF -DIPASIR=ON"
CMSFLAGS="$CMSFLAGS -DSTATICCOMPILE=ON"
D=/tmp/cms${RANDOM}
mkdir -v $D
cd $D
VER=5.11.11
wget https://github.com/msoos/cryptominisat/archive/refs/tags/${VER}.tar.gz
tar xzvf ${VER}.tar.gz
cd cryptominisat-${VER}
mkdir build && cd build
cmake -DCMAKE_INSTALL_PREFIX=${D} ${CMSFLAGS} ..
make -j7
make install
cd ${D}/lib
echo "Testing in "`pwd`
foo >foo.c
gcc -L. -pthread foo.c -o foo -lipasircryptominisat5 && ./foo
foocc >foo.cpp
g++ -L. -pthread foo.cpp -o foocpp -lipasircryptominisat5 && ./foocpp

```

**Comment by msoos** [comment]
Hi,

I would really-really like to help you, but "I'm still unable to build it in C" is tells me so little. I really ask you to put yourself in my shoe. How could I know what possible issues you could be facing if all you tell me is that.

Please help me so I can help you,

Mate

PS: given your script I think the issue is that you are building a static library. If you check my `cmake` flags above you'll see that I never asked it to do a static build. If I do a static build, then there are two options.

Option 1) With C++ compiler. The C++ standard library is not included in the `.a` file, but the C++ compiler will include it. So:

```
$ cat tmp.cpp
#include "stdio.h"

extern "C" {
#include "../src/ipasir.h"
}

const char * ipasir_signature ();
int main() {
    printf("%s", ipasir_signature());
    return 0;
}
```

This compiles flawlessly with:

```
g++ tmp.cpp -static -Llib/ -lipasircryptominisat5 -o mine
```

and runs as expected.

Option 2) With C compiler. Now you will need to link in both stdc++ and "m" (math) library. File is:

```
$ cat tmp.c 
#include "stdio.h"

#include "../src/ipasir.h"

const char * ipasir_signature ();
int main() {
    printf("%s", ipasir_signature());
    return 0;
}
```
Compiles with, notice `-lstdc++` and `-lm`

```
gcc tmp.c -static -Llib/ -lipasircryptominisat5 -lstdc++ -lm -o mine
```

Runs as expected.


Notice that everything that's above is bog-standard. Absolutely nothing out of the ordinary, and I would expect all such projects to build and link this way. If they don't, that's a bug and should be reported to the maintainers. All tutorials and beginners' guides should point to using C++ static libraries in C this way.

Notice that when you compiled it dynamically, the stdc++ library got linked in automatically. This does not happen with static libraries, as per POSIX standard.

**Comment by MikolasJanota** [comment]
Right, sorry about the confusion!!

One option would be to add contidional `extern C` to the header. 

```
#ifdef __cplusplus
extern "C" {
#endif
```

Not sure how kosher that is considered. Armin's got it in cadical (https://github.com/arminbiere/cadical/blob/master/src/ipasir.h).

**Comment by msoos** [comment]
Hi,

AFAIK, there was no confusion.  You simply didn't give enough information in order for me to be able to help you. Funnily enough, you still haven't, as I am still not sure if the above resolved your issue.

Regarding the extern `C thing`, thanks! If you check, the `ipasir.h` I included is copyright:

```
Copyright (c) 2014, Tomas Balyo, Karlsruhe Institute of Technology.
Copyright (c) 2014, Armin Biere, Johannes Kepler University.
```

I have in no way changed it. Hence, they updated `ipasir.h` and forgot to notify people. Sad they forgot to notify people. Anyway, now I added it, yay!

Mate
