### ISSUE TITLE
Assertion is failing

### ISSUE THREAD

**Issue by GregoryMorse** [msoos/cryptominisat#730]
```
/cryptominisat-5.11.12/src/watched.h:106: CMSat::Watched::Watched(CMSat::Lit, bool, int32_t): Assertion `ID < 1LL<< (EFFECTIVELY_USEABLE_BITS-2)' failed.
Aborted (core dumped)
```

Was challenging cryptominisat with a SHA1 instance and after running for a long time, it failed with this.  Is this a bug fixed since 5.11.12 or is the cause of this assertion yet unknown?

Invocation command was:

```
./cryptominisat5 -t 80 sha1.cnf --dumpresult test.out --sampling 58,82,166,883,895,899,742,475,272,285,289,5,14,345,46,104,202,235,1007,906,914,482,486,518,296,303,322,18,56,75,161,882,738,898,741,266,271,1,288,4,333,340,44,97,132,228,889,905,745,472,276,279,295,8,11,17,55,70,159,987,994,919,920,265,498,504,308,310,316,23,41,92,126,224,888,739,911,268,269,278,2,300,10,354
```

The sampling variables were simply the variables I want to ultimately solve - as the Tseitin transform or espresso-logic minimized equivalence substitution variables would seem to be unimportant.  I was thinking a SAT solver should be able to take advantage of the heuristical information of the "true" problem bits rather than treating it generically as extra information should lead to better branching or other heuristics.

**Comment by msoos** [comment]
Ah. Damn. Yeah, this is very annoying. It's because the proof logging clause IDs are reaching the limit. I have just released the new 5.11.14 also with a "largemem" binary, that allows you to run 16x longer (4 more bits!):

https://github.com/msoos/cryptominisat/releases/tag/5.11.14

Check out the "-largemem" binary. I hope that is enough. I'm sorry this happened. You can build it yourself, too, by appending `-DLARGEMEM=ON` to your `cmake`. You should then get:

```
$ ./cryptominisat5
c BreakID not compiled in, disabling
c CryptoMiniSat version 5.11.14
c CMS Copyright (C) 2009-2020 Authors of CryptoMiniSat, see AUTHORS file
c CMS SHA revision c02904b1a85ae3ab54f207607097758582abaf22
c CMS is MIT licensed
c Using VMTF code by Armin Biere from CaDiCaL
c Using Yalsat by Armin Biere, see Balint et al. Improving implementation of SLS solvers [...], SAT'14
c Using WalkSAT by Henry Kautz, see Kautz and Selman Pushing the envelope: planning, propositional logic, and stochastic search, AAAI'96,
c Using code from 'When Boolean Satisfiability Meets Gauss-E. in a Simplex Way'
c       by C.-S. Han and J.-H. Roland Jiang in CAV 2012. Fixes by M. Soos
c Using CCAnr from 'CCAnr: A Conf. Checking Based Local Search Solver [...]'
c       by Shaowei Cai, Chuan Luo, and Kaile Su, SAT 2015
c CMS compilation env CMAKE_CXX_COMPILER = /usr/lib/ccache/bin/c++ | CMAKE_CXX_FLAGS =  -fvisibility=hidden -Wall -Wextra -Wunused -Wsign-compare -fno-omit-frame-pointer -Wtype-limits -Wuninitialized -Wno-deprecated -Wstrict-aliasing -Wpointer-arith -Wpointer-arith -Wformat-nonliteral -Winit-self -Wparentheses -Wunreachable-code -g -Wno-class-memaccess -mpopcnt -msse4.2 -ggdb3 -Wlogical-op -Wrestrict -Wnull-dereference -Wdouble-promotion -Wshadow -Wformat=2 -Wextra-semi -pedantic | COMPILE_DEFINES =  -DLARGE_OFFSETS -DRDB0_ONLY_FEATURES -DUSE_ZLIB -DYALSAT_FPU | STATICCOMPILE = ON | ONLY_SIMPLE = OFF | Boost_FOUND = TRUE | STATS = OFF | SQLITE3_FOUND =  | ZLIB_FOUND = TRUE | VALGRIND_FOUND =  | ENABLE_TESTING = OFF | M4RI_FOUND =  | NOM4RI = ON | SLOW_DEBUG = OFF | ENABLE_ASSERTIONS = ON | PYTHON_EXECUTABLE =  | PYTHON_LIBRARY =  | PYTHON_INCLUDE_DIRS =  | MY_TARGETS =  | LARGEMEM = ON | LIMITMEM = OFF | BREAKID_LIBRARIES =  | BREAKID-VER = . | BOSPHORUS_LIBRARIES =  | BOSPH-VER = . | compilation date time = Sep 23 2023 15:19:57
```

Notice the `LARGEMEM = ON`.

Regarding sampling variables. I think they don't do what you may think they do? They simply force the solver not to eliminate those variables. Internally, that constrains the solver, which may not be ideal. It would solve those variables, too.  So I'd likely remove that part of the command line.

I like the `-t 80`, kinda crazy it actually ran with that many threads :rofl:  Not sure it's the best solver to run with those many threads, though. I think you probably would benefit from using https://github.com/arminbiere/gimsatul -- I'm basically talking against my own interests here, but for your interest, so maybe that's OK. That gimsatul thing is pretty cool and should likely work better for 80 threads. I'd also very much try out https://github.com/marijnheule/CnC again by Armin Biere (and this time together with Marijn Heule), two giants of the field.

Good luck! I hope the above helped. I am closing, but you can re-open if there's some further issue :)

**Comment by GregoryMorse** [comment]
Wow, thank you for this thorough explanation.  So LARGEMEM is definitely worth it in this case with a large problem over a lot of processor cores.  Also thanks for pointing me to the parallel solvers, yours does work great with many threads I even tried the limit for the server at 96.  Thanks for the hints will also try out the other solvers, yours is certainly one of the best and easiest to use.  The solvers from the SAT competition I was finding to be buggy/useless interestingly enough.  You know better :).

Ah so I thought sampling was doing some sort of probabilistic analysis probing.  Indeed not the best choice then.  Is there really no way for a SAT solver to take advantage of knowing which variables represent the goal/'secret' bits?

**Comment by msoos** [comment]
Hi,

Glad to hear I helped. Yeah, do try out the other solvers. Regarding the secret bits -- the answer is mostly no. That's because the way a SAT solver branches ought to be done based on how the system is performing, which is likely not how the system is thought to be performing by the original creator of the problem. SAT solvers work in mysterious ways :D

Glad again that I could help,

Mate

**Comment by GregoryMorse** [comment]
Just a note: The Cube and Conquer solver doesnt seem to be multi-threaded?

**Comment by msoos** [comment]
Sorry, you need to use treengeling from: https://github.com/arminbiere/lingeling that's the cube-and-conquer using lookahead+lingeling. You can also try plingeling from the same repository -- it builds lingeling, plingeling, and treengeling.

**Comment by GregoryMorse** [comment]
Yup, that is the one :).  Your wisdom on the problem variables not being helpful is very interesting.  Its counter intuitive in many ways.

When searching for a preimage though, I would think sending through a large set of random samples, would allow the SAT solver to detect:
1) variables that are always True/False with high probability which might make sense to work on prioritizing for elimination?
2) variables that are always equal/not equal to other variables with high probability.

Not that I expect this is anything very interesting.  Quite sure everyone has thought of this idea, experimented with it, maybe made some limited cryptanalysis breakthroughs here and there like in e.g. md5.  But its interesting solvers don't consider it as a warmup heuristic?

**Comment by GregoryMorse** [comment]
Oh also, it might be helpful to make the relevant assertion warnings mention the LARGEMEM option e.g. `please make sure you are building with LARGEMEM enabled` as the recommended solution to this particular issue.

**Comment by msoos** [comment]
Yay, just added that hint!
