### ISSUE TITLE
MPI compilation doesn't work

### ISSUE THREAD

**Issue by marino-mrc** [msoos/cryptominisat#733]
Hi,
the MPI compilation fails because there are 2 main problems:

1) in src/datasyncserver.h the following function is missing:

`bool add_red_clause(const std::vector<Lit>& lits);` 
I implemented this function with a trivial code because it seems the function is not really used:

`bool CMSat::DataSyncServer::add_red_clause(const std::vector<Lit>& lits)
{
    assert(false);
    return false;
}
`

2) in src/main_mpi.cpp the following directive is missing:

`using namespace CMSat;`

After fixing the points above, I was able to compile and run cryptominisat5_mpi. The implementation works at a first glance, but it doesn't support guiding paths (assumptions). It could be great to have that feature, but I'm struggling with an efficient strategy for storing offline the paths already tested. I mean, if the search space is very high ( bigger than 2^128), how can I store in an efficient way the information?

Thanks,
Marco

**Comment by msoos** [comment]
Hi,

MPI is not really maintained, sorry. Assumptions is not really guiding paths I think? Or maybe it is and I am behind the terminology... I never heard that :laughing: Anyway, it is not supported, MPI is basically unsupported. I could make it work, but who would care? The issue here is that it would take me 4h to fix it properly, then about 1 week/year to maintain it. However, almost nobody ever uses it for more than once to try it out, mostly for fun. I prefer spending my time on things that people really truly care about. Besides, the MPI thing was mostly just for fun.

If you create a PR to fix the issues so it works right now, then I would be very happy to merge those PRs! However, I can't promise maintain it. Looking forward to the PRs,

Mate
