### ISSUE TITLE
Setting Literal Polarity

### ISSUE THREAD

**Issue by gaspard-quenard** [msoos/cryptominisat#737]
Hello,

I've been working on incrementally solving a formula by utilizing cryptominisat, progressively incorporating more clauses with each iteration. But there are literals that I would prefer to be false and other that I would prefer to be true in this formula. This means that even when the current formula is satisfiable, I would like to influence the assignment of certain literals to false to prevent them from persisting as I introduce new clauses (I want the SAT solver to still be able to choose them, but I would prefer if it takes an alternative).

Could you tell me if there's a way to adjust the polarity of a literal in between consecutive SAT solver calls? I've looked through the documentation but haven't come across a dedicated function for this purpose. I did stumble upon set_var_weight, but I'm uncertain if it aligns with what I need. Any guidance on this matter would be greatly appreciated.

**Comment by msoos** [comment]
Hi,

In general, it would be possible to do what you are trying to achieve. However, it may lead to cost that is extremely large, maybe making your solving 100x slower. Most people wouldn't like that, I think :( The issue is that people would add these kind of polarity semi-requirements in the hope that they help, and then perhaps conclude that SAT solvers are slow. Which would be kinda true.... but also not :D Sometimes, users are not very well aware of the limitations of SAT solving and can make mistakes in using SAT solvers. So I don't have this option mostly because I have seen some very sad things where people thought they were helping the solver with e.g. setting polarities of variables, thereby making solving a LOT slower.

In general, I think you may be OK with trying to solve with assumptions! Have you tried solving with the literals you want as assumptions? Maybe that works for you? It could very well be a good try. I know it's not the same, but maybe it works? Try :) It's worth trying. Check out the example with assumptions. I hope it will help. If not, I can also explain in a follow-up comment. Also, what's nice about assumptions is that you will be able to swap out the SAT solver underneath, as all SAT solvers support assumptions :)

Note that I could potentially add this option. It would not be that hard, but also not trivial. And the guarantees it would give would be weak. And it could really make things slower. But I'm a bit busy now. Maybe you could use the assumptions trick instead at first?

**Comment by gaspard-quenard** [comment]
Hi,

Thank you very much for the detailed answer! :)

Yes, I have thought about using assumptions, but it's not so easy to implement them smartly in my case. My objective is to minimize the appearance of certain literals in the current solution, although I know that it is very likely some of them will be true. Initially, my idea was to run the SAT solver without assumptions, obtain a solution, and then add assumptions for all the literals that I do not want in the current solution. However, if I assume that all the unwanted literals are false, I am aware that it will probably lead to no solution. And if I add assumptions one by one (one SAT call with one assumption regarding an unwanted literal), the unwanted literal could simply be replaced by another undesirable literal in the new solution. Nevertheless, it can still be utilized with methods like this. But since making SAT calls in such a manner is quite expensive, I wanted to know if another alternative was possible. From what you've said, it seems very likely that, in fact, this technique could be much quicker than setting the polarities.

One last question, though: would it be slower even when we only set the polarity upon initializing a new literal (i.e., not changing the polarity of a literal if a SAT call has already been made on a formula containing this literal)? For example, instead of using the polarity mode negative for all new literals, could I set the default polarity mode to positive for all literals and only set the polarity mode to negative for those I do not want ?

**Comment by msoos** [comment]
Hi,

It would probably be possible, and it may work. However, unfortunately I don't have the time available to do this :( I'm sorry. I believe the new IPASIR library will have this kind of interface. So maybe some solvers will start supporting it. Sorry, but currently I am just under the weather, too many things to do. I hope you understand.

Mate

**Comment by gaspard-quenard** [comment]
Hi,

No problem, thank you for your time :)
