### ISSUE TITLE
Weighted variables

### ISSUE THREAD

**Issue by na3na3na** [msoos/cryptominisat#738]
Hi Mate,

Is there a way to assign weightings to the variables for the solver to prioritise when solving? Something like forcing the solver to go down certain branches before exploring other branches.

Thanks!

**Comment by msoos** [comment]
Hi,

Sorry, no. In general, it would be a bad idea. Solvers behave in strange ways. If CryptoMiniSat let people do that, it would almost always make solving 10x-100x slower and people would be very surprised and upset. So this is not an option, because even people who write the solver and the problem have no idea what weights to give. I personally don't like to give tools for people to make a minefield for themselves :) So I cannot support this option, because it would lead to a lot of pain and confusion. I hope you understand :) Cheers,,

Mate
