### ISSUE TITLE
How to estimate the SAT Solving time?

### ISSUE THREAD

**Issue by Gary-oak-Star** [msoos/cryptominisat#740]
Hello msoos,

I am currently conducting some experiments to speed up SAT solving in cryptominisat. However, since I am running the experiment on a shared server, the computational resources are sometimes occupied by others, which affects the accuracy of time calculation. I read some papers and found that the number of division variables, literal block distance, or branching information may help estimate the SAT solving time rather than directly using time.

Do you have any suggestions on how to achieve this in cryptominisat's C++ or Python binding?

**Comment by msoos** [comment]
Nothing helps estimate if it’s an unknown problem. Then, the only thing
that can help estimate is by going to a witch doctor and asking them for
snake oil, that you have to burn at midnight on New Year’s Eve. Then you’ll
know. Otherwise, no. If it’s a known problem, then you can estimate
yourself by measuring smaller, easier problems and extrapolating. Just my
two cents,

Mate

**Comment by msoos** [comment]
CPU time is the only measurement you can rely on. The other stuff is NOT
well-correlated AT ALL. Using that is akin to drinking snake oil. Do that
at your own peril. Use “/usr/bin/time —verbose MYPROGRAM MYOPTIONS” and
then you get the ACTUAL cpu time spent on your executable even in a shared
environment (sure, there’ll be noise but it’ll be not too bad). Check out
the manual for that binary. DO NOT use “time” that’s DIFFERENT(!). Good
luck,

Mate
