### ISSUE TITLE
Blocked clause until UNSAT searcher

### ISSUE THREAD

**Issue by GregoryMorse** [msoos/cryptominisat#742]
I'm not sure why SAT solvers have not implemented this as it seems to have some critical applications.
For example Maximally-Reduce-Faster on page 5:
https://www.cs.cmu.edu/~emc/papers/Conference%20Papers/SAT-Based%20Algorithms%20for%20Logic%20Minimization.pdf

Disrupting a SAT solver is expensive in terms of lost state.  While telling the SAT solver to automatically block clauses until UNSAT is really something that belongs integrated in the solver.  The solution is in fact the blocked clauses.

For example, I want to find a functional equivalence between f(x) and a function I want to construct from a generic 'fabric' g(x).  Where x is intractably large e.g. 32 Boolean variables.  Proving functional equivalence requires f(x) XOR g(x) is UNSAT.  It cannot be phrased in terms of satisfiability.  This is fine if g(x) is known in advance but not if you are constructing it and proving equivalence together.

Is there any reason not to make this as a feature request?  It seems this concept crops up in a variety of applications stemming from functional equivalence.

**Comment by msoos** [comment]
So I have good news for you! Friends have published this: https://github.com/yogevshalmon/allsat-circuits And it's available right now, and waaaaaay better than that thing in that paper. It generates a minimal DNF, which is a 2-level minimal circuit, exactly what that paper wants to do, but better ;)

As for functional equivalence, you can do something better, by the way! It's a trick that's in our Arjun tool. You set all inputs to be equivalent (a XOR b = false for all input variables), and assert that output1 = 1, output2 = 0. You then do another check,  output1 = 0, output2 = 1. If both are UNSAT, you are done. Notice that you can do that with assumptions, and so you can reuse knowledge from previous runs. Setting them to 1/0 and 0/1 tends to run a lot faster than doing the XOR. Since you can do it with assumptions, you don't lose information.

Now, here comes the kicker. If I understood well what you wrote: what you want is 100% already inside all SAT solvers that can do assumptions-based solving. Yes. Just add a new variable vE. Now, all the clauses you add should have vE inside:

vE 1 2 44 55 0
vE 33 -12 459 0

etc. Now, you solve with assumption vE=false. Once it proves UNSAT, you just add the clause vE=true. That will remove all those clauses. And you can keep all knowledge it accumulated! I don't know what that paper is doing, but if they do anything else, they are doing it wrong :D This is how it's done by all researchers I know, and in fact that's how I do it with Arjun: https://github.com/meelgroup/arjun So you can remove clauses anytime. All the time. Just need to make sure you add the variable in the clause in advance. Maybe I'll write a blog post about this trick, because I have seen many people being confused, thinking they can't remove clauses from SAT solvers. When in fact you can, and not only you can, but many-many tools employ this trick.

I hope the above helped,

Mate

**Comment by GregoryMorse** [comment]
Yes that is very nice.  So it sounds like Espresso and Bosphorus are no longer the state of the art for 2 level SOP or POS minimization.  However you marketed arjun properly, it's not very explicitly stated on their page about this important usage.

So I came across this idea of doing two UNSAT with both outputs here where they call the idea semantic entailment: https://www.iaik.tugraz.at/wp-content/uploads/2022/01/LaC_SS22_Chapter3.pdf  - Decide entailment using satisfiability.  Decide equivalence using entailment.

What I didn't realize is why it might be useful :).  Sometimes my mind is in only one call to the SAT oracle mode.  But with UNSAT that's a non productive perspective as seen with things like counter example guided optimization.

So your idea of using assumptions makes this feature as you mention already implemented.  I looked at that and should have realized this bridged the gap.  Counter example driven optimization applications also will work much better in the future by optimizing solver efficiency using assumptions.

The blog post is worth it if you have the time, i have read some of your posts in the past.  Practical advice is often hard to come by.  But there is a decent amount of interest in this area.  Thanks as always.
